### ISSUE TITLE
Zeilenansicht Abzüge & verwandte Arbeiten

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#10]
- Abzüge etwas kleiner    
- nur eine Zeile Abzüge anzeigen, bei mehr als 5 Objekten Pfeil zum   Ausklappen wie bei Werknormdaten
--

**Comment by jhfpereira** [comment]
Aktueller Stand:

Vorher:
![Bildschirmfoto 2020-04-12 um 19 50 52](https://user-images.githubusercontent.com/1864692/79076029-120f9980-7cf7-11ea-9bca-bc7748182445.png)

Nachher:
![Bildschirmfoto 2020-04-12 um 19 51 10](https://user-images.githubusercontent.com/1864692/79076031-1936a780-7cf7-11ea-877c-3d655a612d29.png)

Momentan überlappt der Pfeil zum Aufklappen das letzte Element in der Reihe etwas.
