### ISSUE TITLE
Angaben weichen ab zwischen ein- und ausgeklapptem Feld am Frontend

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#100]
### URL of the buggy page?

https://lucascranach.org/de/ANO_H-NONE-022/

### Contact Details

DG

### What happened?

Im Feld Datierung steht diese inhaltlich korrekt Info:
![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/b959c165-0d21-45e7-9cab-85311417248c)

Wird das Feld ausgeklappt, aber diese falsche Info:
![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/7d2fec2a-56cf-4c6b-a740-e8f72f410a91)

TMS-seitig ist alles korrekt eingetragen

**Comment by markusalterauge** [comment]
Tatsächlich sollte da nur "Juni 1521" stehen. Durch das html wird noch ein 1. davor gehangen, weil es an erster Stelle steht. Fixe ich erst mal händisch

**Comment by dangoerr** [comment]
Das ist seltsam, da "Juni 1521" in TMS nirgendwo vermerkt ist (noch ein alter Eintrag?). Danke für's händische Fixen.

**Comment by dangoerr** [comment]
Jetzt zeigt das Datierungsfeld von https://lucascranach.org/de/LC_HVI-9_8 ein ähnliches Problem:
Eingeklappt:
![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/5f8fdf24-7616-4dfc-bd3c-06d3e31e0823)
Ausgeklappt:
![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/ca82e6c1-fa01-4ca1-85bd-7f03f5dbb9fa)

Aus 18. Jahrhundert wird 1. Jahrhundert...

**Comment by markusalterauge** [comment]
https://lucascranach.org/intern/artefacts/de/LC_HVI-9_8/ wir müssen es noch auf den nicht öffentlichen Bereich anwenden.
