### ISSUE TITLE
Name Cranachs wird immer noch unvollständig angezeigt

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#101]
### URL of the buggy page?

z. B. https://lucascranach.org/de/LC_HVI-107_132/

### Contact Details

DG

### What happened?

Bei der Anzeige Cranachs etwa im Feld Zuschreibung, wird (im zugeklappten Zustand) nur "Lucas Cranach" angezeigt, das Suffix "der Ältere" aber nicht. Wird das Feld ausgeklappt, steht dort weiterhin "Lucas Cranach <der Ältere>, obwohl dies schon seit dem letzten Export TMS-seitig behoben wurde. Bei der englischen Spracheinstellung dagegen ist es vollständig "Lucas Cranach the Elder".
Bei "Lucas Cranach der Jüngere" tritt tat Problem ebenfalls nicht auf.

**Comment by markusalterauge** [comment]
Hi, das müsste jetzt passen, bitte nochmal überprüfen.

**Comment by dangoerr** [comment]
Super, bei den Gemälden passt es jetzt tatsächlich, vielen Dank! Jetzt sind es nur noch die Graphiken, die die unvollständige Anzeige haben, z. B. hier:
https://lucascranach.org/de/LC_HVI-9_8

**Comment by markusalterauge** [comment]
geht es dort auch um die Zuschreibung? Bei mir wird die Zuschreibung bei der Grafik: https://lucascranach.org/de/LC_HVI-9_8 richtig angezeigt.

**Comment by dangoerr** [comment]
Sorry, nach Cache/Cookie-Löschung dann bei mir auch. Jetzt zeigt aber das Datierungsfeld von https://lucascranach.org/de/LC_HVI-9_8 ein ähnliches Problem wie bei Issue #100:
Eingeklappt:
![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/5f8fdf24-7616-4dfc-bd3c-06d3e31e0823)
Ausgeklappt:
![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/ca82e6c1-fa01-4ca1-85bd-7f03f5dbb9fa)

Aus 18. Jahrhundert wird 1. Jahrhundert...

**Comment by markusalterauge** [comment]
Ah okay, ja das hab ich gesehen, das ist allerdings dieses issue: #100

**Comment by dangoerr** [comment]
> Sorry, nach Cache/Cookie-Löschung dann bei mir auch. Jetzt zeigt aber das Datierungsfeld von https://lucascranach.org/de/LC_HVI-9_8 ein ähnliches Problem wie bei Issue #100: Eingeklappt: ![grafik](https://user-images.githubusercontent.com/91158095/283496351-5f8fdf24-7616-4dfc-bd3c-06d3e31e0823.png) Ausgeklappt: ![grafik](https://user-images.githubusercontent.com/91158095/283496555-ca82e6c1-fa01-4ca1-85bd-7f03f5dbb9fa.png)
> 
> Aus 18. Jahrhundert wird 1. Jahrhundert...

**Comment by dangoerr** [comment]
Danke, scheint jetzt überall wieder korrekt zu sein!
