### ISSUE TITLE
G_DE_GNMN_K21148 wird nicht angezeigt

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#103]
### URL of the buggy page?

https://lucascranach.org/de/MIB_H-NONE-002/

### Contact Details

DG

### What happened?

Auf https://lucascranach.org/de/MIB_H-NONE-002/ werden aktuell sechs Abzüge angezeigt, es fehlt dabei ein siebter (G_DE_GNMN_K21148), der inhaltlich nicht unwichtig ist, da wir uns oben im Text auf ihn beziehen.
Wie es aussieht, ist da mit den Bildordner was durcheinander geraten, der 01_Overall-Ordner liegt, soweit ich sehe, im 02_Reverse-Ordner. Falls ich das neu sortieren soll, stellt mir den Ordner einfach bereit und ihr bekommt dann einen korrekten Ordner zurück.

**Comment by dangoerr** [comment]
@cnoss Die korrekt geordneten Daten liegen im Verzeichnis /home/dgoerres/Bitte austauschen auf dem Server. Siehe Comments #111

**Comment by yannic-bruegger** [comment]
Ich klaue mir das Issue mal und mache es nach bestem Wissen und Gewissen 👍

**Comment by yannic-bruegger** [comment]
Ich habe den Overview-Ordner hinzugefügt. @cnoss muss noch etwas gemacht werden außer dem neubauen der artefact Applikation? Muss ide json im Ordner vorher angepasst werden?

**Comment by cnoss** [comment]
ist nun da … der Prozess ist leider noch etwas komplex … ich dokumentiere den mal, bzw. vervollständige die Doku mal:
https://github.com/lucascranach/cda-orga/wiki/Import-cda-2022
