### ISSUE TITLE
Bei den Graphikdaten scheinen in der internen unveröffentlichte Vorschau (Preview) noch keine neuen Daten vorzuliegen

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#104]
### URL of the buggy page?

https://lucascranach.org/intern/artefacts/de/LC_HVI-56_79/

### Contact Details

DG

### What happened?

Bei den Graphikdaten scheinen in der internen unveröffentlichte Vorschau (Preview) noch keine neuen Daten vorzuliegen. Den Datensatz LC_HVI-56_79 habe ich ja umfassend aufbereitet für den aktuellen Export, die Daten sind aber größtenteils noch auf dem alten Stand. Das Feld Sortierreihenfolge scheint aktualisiert (da der Datensatz auf Seite 1 der Übersicht erscheint), ein Feld wie Datierung z. B. (wo 11 Auflagen eingetragen sind) dagegen nicht.

**Comment by markusalterauge** [comment]
@dangoerr, bitte noch mal nachschauen, ob es jetzt passt.

**Comment by dangoerr** [comment]
Danke, ja, die Daten sind jetzt da, allerdings findet dabei noch keine Sprachunterscheidung statt. Es sind also alle Einträge in der deutschen und englischen Spracheinstellung zu sehen.

**Comment by dangoerr** [comment]
Das ist übrigens nur bei der eigentlichen Jahreszahl ablesbar, der darauf folgende Langtext "a)...", b)..." usw. soll in beiden Varianten bis auf Weiteres Deutsch sein (da uns noch keine Übersetzung vorliegt).
