### ISSUE TITLE
Funktion Bildvergleich von Abbildungen z.Z. nicht funktionsfähig 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#105]
### URL of the buggy page?

https://lucascranach.org/de/search/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Kann im Moment auf der Objektebene keine Abb. in den persönlichen Ordner übernehmen, um einen Bildvergleich vorzunehmen.

**Comment by cnoss** [comment]
Fixed. Ist beim Umzug verloren gegangen
