### ISSUE TITLE
Bearbeiten von https://lucascranach.org/index.php/luther/literatur im CMS nicht möglich

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#107]
### URL of the buggy page?

https://lucascranach.org/index.php/luther/literatur

### Contact Details

DG

### What happened?

Der Versuch auf der Seite in Concrete 5 Änderungen vorzunehmen, führt immer zu dieser Fehlermeldung:

<html><body>
<span id="ui-id-1" class="ui-dialog-title">Fehler</span><div id="ccm-popup-alert-message"><p class="text-danger"><strong>Undefined variable $Abbildung_o</strong></p><p class="text-muted">Details</p>
/var/www/html/cms/application/blocks/zeile_mit_bild/form.php(13): Whoops\Exception\ErrorException->null |  
-- | --
/var/www/html/cms/application/blocks/zeile_mit_bild/form.php(13): Whoops\Run->handleError |  
/var/www/html/cms/concrete/src/Block/View/BlockView.php(380): null->include |  
/var/www/html/cms/application/blocks/zeile_mit_bild/edit.php(2): Concrete\Core\Block\View\BlockView->inc |  
/var/www/html/cms/concrete/src/Block/View/BlockView.php(267): null->include |  
/var/www/html/cms/concrete/src/View/AbstractView.php(164): Concrete\Core\Block\View\BlockView->renderViewContents |  
/var/www/html/cms/concrete/views/dialogs/block/edit.php(33): Concrete\Core\View\AbstractView->render |  
/var/www/html/cms/concrete/src/View/View.php(318): null->include |  
/var/www/html/cms/concrete/src/View/View.php(296): Concrete\Core\View\View->renderInnerContents |  
/var/www/html/cms/concrete/src/View/DialogView.php(34): Concrete\Core\View\View->renderViewContents |  
/var/www/html/cms/concrete/src/View/AbstractView.php(164): Concrete\Core\View\DialogView->renderViewContents |  
/var/www/html/cms/concrete/src/Routing/ControllerRouteAction.php(82): Concrete\Core\View\AbstractView->render |  
/var/www/html/cms/concrete/src/Http/RouteDispatcher.php(37): Concrete\Core\Routing\ControllerRouteAction->execute |  
/var/www/html/cms/concrete/src/Http/Middleware/DispatcherDelegate.php(39): Concrete\Core\Http\RouteDispatcher->dispatch |  
/var/www/html/cms/concrete/src/Http/Middleware/MiddlewareStack.php(86):  Concrete\Core\Http\Middleware\DispatcherDelegate->next |  
/var/www/html/cms/concrete/src/Http/DefaultDispatcher.php(127): Concrete\Core\Http\Middleware\MiddlewareStack->process |  
/var/www/html/cms/concrete/src/Http/DefaultDispatcher.php(60): Concrete\Core\Http\DefaultDispatcher->handleDispatch |  
/var/www/html/cms/concrete/src/Http/Middleware/DispatcherDelegate.php(39): Concrete\Core\Http\DefaultDispatcher->dispatch |  
/var/www/html/cms/concrete/src/Http/Middleware/FrameOptionsMiddleware.php(39):  Concrete\Core\Http\Middleware\DispatcherDelegate->next |  
/var/www/html/cms/concrete/src/Http/Middleware/MiddlewareDelegate.php(50):  Concrete\Core\Http\Middleware\FrameOptionsMiddleware->process |  
/var/www/html/cms/concrete/src/Http/Middleware/StrictTransportSecurityMiddleware.php(36):  Concrete\Core\Http\Middleware\MiddlewareDelegate->next |  
/var/www/html/cms/concrete/src/Http/Middleware/MiddlewareDelegate.php(50):   Concrete\Core\Http\Middleware\StrictTransportSecurityMiddleware->process |  
/var/www/html/cms/concrete/src/Http/Middleware/ContentSecurityPolicyMiddleware.php(36):  Concrete\Core\Http\Middleware\MiddlewareDelegate->next |  
/var/www/html/cms/concrete/src/Http/Middleware/MiddlewareDelegate.php(50):   Concrete\Core\Http\Middleware\ContentSecurityPolicyMiddleware->process |  
/var/www/html/cms/concrete/src/Http/Middleware/CookieMiddleware.php(35):  Concrete\Core\Http\Middleware\MiddlewareDelegate->next |  
/var/www/html/cms/concrete/src/Http/Middleware/MiddlewareDelegate.php(50):  Concrete\Core\Http\Middleware\CookieMiddleware->process |  
/var/www/html/cms/concrete/src/Http/Middleware/ApplicationMiddleware.php(29):  Concrete\Core\Http\Middleware\MiddlewareDelegate->next |  
/var/www/html/cms/concrete/src/Http/Middleware/MiddlewareDelegate.php(50):  Concrete\Core\Http\Middleware\ApplicationMiddleware->process |  
/var/www/html/cms/concrete/src/Http/Middleware/MiddlewareStack.php(86):  Concrete\Core\Http\Middleware\MiddlewareDelegate->next |  
/var/www/html/cms/concrete/src/Http/DefaultServer.php(85): Concrete\Core\Http\Middleware\MiddlewareStack->process |  
/var/www/html/cms/concrete/src/Foundation/Runtime/Run/DefaultRunner.php(128): Concrete\Core\Http\DefaultServer->handleRequest |  
/var/www/html/cms/concrete/src/Foundation/Runtime/DefaultRuntime.php(102):  Concrete\Core\Foundation\Runtime\Run\DefaultRunner->run |  
/var/www/html/cms/concrete/dispatcher.php(45): Concrete\Core\Foundation\Runtime\DefaultRuntime->run |  
/var/www/html/cms/index.php(2): null->require

</div>
</body>
</html>

**Comment by markusalterauge** [comment]
Sollte jetzt wieder funktionieren.

Da kein Bild vorhanden ist, aber ein Bild verlangt wurde, habe ich zu Anfang Abbildung_o = false gesetzt. Falls ein Bild vorhanden ist, wird der Abbildung_o ein Wert zugefügt.

**Comment by dangoerr** [comment]
Super, danke!!
