### ISSUE TITLE
Bitte Backup des Websiten-Bereichs

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#109]
### URL of the buggy page?

z. B. https://lucascranach.org/index.php/luther/einleitung

### Contact Details

DG

### What happened?

Da das CMS in letzter Zeit viele Probleme gemacht hat, ich aber dank der Hilfe von Markus trotzdem nun alle älteren Seiten auf den neuesten Stand bringen konnte, wäre jetzt ein guter Zeitpunkt um vom ganzen redaktionellen Bereich ein Backup anzufertigen. Falls das CMS später größere Probleme macht, könnten wir auf den heutigen inhaltlich vollständigen Stand zurückgehen.

**Comment by yannic-bruegger** [comment]
Schließe das mal nachträglich ab. Nicht wundern :) Ich baue gleich mal eine Automatisierung, die das macht, wenn das Issue in einen neuen Status gezogen wird.
