### ISSUE TITLE
Zuschreibung in Werknormdaten

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#11]
Rubrik „Zuschreibung“: Hinter „Lucas Cranach der Ältere“ Pfeil einfügen, wenn dieser  angeklickt wird, dann öffnet sich nach unten eine Tabellenansicht mit den  Feldern:  
- Inventor: Eintrag aus Inventor, dahinter das   zugehörige Kommentarfeld   
- Formscheider: Eintrag aus Formschneider,   dahinter das zugehörige Kommentarfeld   

Mehr als zwei Einträge und   dahinter die zugehörigen Kommentarfelder möglich
--

**Comment by jhfpereira** [comment]
Für die Auflistung der involvierten Personen, habe ich die bestehende DefinitionList genommen, wobei die Personen dann als erstenEinträge aufgelistet werden.

Aktueller Stand:

Geschlossen:
![Bildschirmfoto 2020-03-15 um 22 05 57](https://user-images.githubusercontent.com/1864692/76710615-3cc2fe00-6709-11ea-93a9-6d47083f967d.png)

Geöffnet:
![Bildschirmfoto 2020-03-15 um 22 06 04](https://user-images.githubusercontent.com/1864692/76710626-49475680-6709-11ea-86aa-e1bd67a9eea1.png)

**Comment by jhfpereira** [comment]
Für Ausgabe der Einträge eine Tabelle eingeführt, die nur sichtbar wird, wenn auf den Pfeil hinter dem Namen geklickt wird. Mit diesem Ansatz wird nicht mehr die bisherige DefinitionList für die Ausgabe missbrauch. Evtl. muss noch Hand an den Abständen vorgenommen werden. Hoffe aber es entspricht nun eher der Vorstellung.

Aktueller Stand:

Geöffnet:
![Bildschirmfoto 2020-04-12 um 18 19 21](https://user-images.githubusercontent.com/1864692/79074001-2a2cec00-7cea-11ea-97f1-c716d100fc5f.png)
