### ISSUE TITLE
Weiterer CMS-Block, der nicht editierbar ist

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#110]
### URL of the buggy page?

https://lucascranach.org/index.php/luther/einleitung

### Contact Details

DG

### What happened?

Hi, könntest Du bei Gelegenheit für den Block "III. Dank" noch einmal schauen. Es ist die selbe Fehlermeldung wie zuletzt bei Konkordanz/Literatur, ebenfalls ohne Abb., wahrscheinlich der gleiche Fix...Danke!

**Comment by markusalterauge** [comment]
Sollte jetzt wieder funktionieren.

**Comment by dangoerr** [comment]
Danke!
