### ISSUE TITLE
Fehlerhafte Anzeige links

### ISSUE THREAD

**Issue by cdaJana** [lucascranach/cda-orga#112]
### URL of the buggy page?

z.B. https://lucascranach.org/de/AU_NGV_4700-3

### Contact Details

JH

### What happened?

Hallo Christian,
der Vollständigkeit halber packe ich meine emails zu dem Thema auch in GitHub:
beim Korrekturlesen des letzten Ex-/Imports ist mir aufgefallen, dass bei den neuen Gemälden im internen Bereich die links nicht korrekt angezeigt werden. Im TMS sind die links immer identisch eingegeben, also "[...](..)". Habe dir eine Übersicht aller betroffenen Felder sowie einen Screenshot dazu angehängt.
Bei allen bislang geprüften Daten sind immer dieselben Felder vom selben Fehler betroffen. Es sieht im Seitenquelltext so aus, als fehlt bei den "Inschriften" das Anchor-Element. Bei anderen Feldern wie "Maße" oder "Provenienz" funktioniert der link aber die eckigen Klammern sind verschwunden.
Nach weiterer Prüfung hatten sich noch mehr Unstimmigkeiten aufgetan - bei Datierung und Zuschreibung - siehe Screenshots.

Betroffen sind nicht nur links im internen Bereich, sondern auch am Frontend.

### Additional context & Screenshots

![fehlerhafte Anzeige der Links](https://github.com/lucascranach/cda-orga/assets/153098069/57c5469b-44c8-4484-aecc-6def4de48a0b)
![fehlerhafte Anzeige Link bei Datierung 1](https://github.com/lucascranach/cda-orga/assets/153098069/23768b03-8c0f-4cfc-9922-82feb3c03a72)
![fehlerhafte Anzeige Link bei Datierung 2](https://github.com/lucascranach/cda-orga/assets/153098069/4d6c832a-a5ab-4de8-863f-2dcf5bf2fb68)
![fehlerhafte link-Anzeige bei Zuschreibung](https://github.com/lucascranach/cda-orga/assets/153098069/0d8c7330-95b2-4ba3-bc24-5d8eea59a464)
[fehlerhafte Anzeige der links_3.11.23.docx](https://github.com/lucascranach/cda-orga/files/13587327/fehlerhafte.Anzeige.der.links_3.11.23.docx)

**Comment by yannic-bruegger** [comment]
Ich schnappe mir das Issue mal und schaue rein

**Comment by yannic-bruegger** [comment]
Sollte gefixt sein. Leider kann ich es dir noch nicht zum Testen geben, da Gunnar gerade einen anderen Bugfix prüft. Ich lasse es dich wissen, wenn getestet werden kann :) VG

**Comment by cdaJana** [comment]
Danke für das Update! Bin gespannt

**Comment by yannic-bruegger** [comment]
So @cdaJana, die neue Version ist jetzt im internen Bereich. Bitte einmal schauen ob jetzt die Probleme behoben sind und ob alles noch an Ort und Stelle ist. Danke dir!

Hier ein Beispiel: https://lucascranach.org/intern/artefacts/de/PRIVATE_NONE-P614/

**Comment by cdaJana** [comment]
Danke für die Info, werde es mir nächste Woche ansehen
