### ISSUE TITLE
Fehlerhafte Anzeige der Zuschreibung

### ISSUE THREAD

**Issue by cdaJana** [lucascranach/cda-orga#115]
### URL of the buggy page?

https://lucascranach.org/intern/artefacts/de/PRIVATE_NONE-P605/

### Contact Details

JH

### What happened?

Bei diesem Datensatz werden bei der Zuschreibung in auf- und zugeklapptem Zustand unterschiedliche Informationen angezeigt.

### Additional context & Screenshots

![fehlerhafte Anzeige bei Zuschreibung - zugeklappt](https://github.com/lucascranach/cda-orga/assets/153098069/613dee6c-b4f6-43c2-96bc-812288094d41)
![fehlerhafte Anzeige bei Zuschreibung - aufgeklappt](https://github.com/lucascranach/cda-orga/assets/153098069/61eafe3b-a3b9-47e0-9d43-22eb0d6a87e4)

**Comment by cdaJana** [comment]
Habe einen weiteren Datensatz mit fhelerhafter Anezige der Zuschreibung gefunden. In diesem Falle fehlt der Pfeil zum aufklappen und anzeigen der Quellen.
![fehlerhafte Anzeige Zuschreibung - keine Quellenangaben aufklappbar](https://github.com/lucascranach/cda-orga/assets/153098069/c737650e-740a-4078-9e04-de07896ea3fb)

**Comment by cnoss** [comment]
Da kommt bei uns in den Daten folgendes an:

![Image](https://github.com/lucascranach/cda-orga/assets/2807738/99fb68df-3c76-4ded-ae3d-f54797672652)

Der erste Eintrag sieht komisch aus … @dangoerr @cdaJana können wir uns das mal zusammen anschauen, oder könnt ihr noch mal im TMS gucken, ob da alles korrekt eingetragen ist?

**Comment by dangoerr** [comment]
Bei https://lucascranach.org/de/PRIVATE_NONE-P605/ ist korrekterweise "Unbekannt"/"Unknown" und zusätzlich als Suffix eingetragen, das scheint ja schon nicht anzukommen. Der zweite Eintrag "Lucas Cranach der Jüngere" ist ja da.
Ich bin heute am Rechner, melde Dich, dann können wir zusammen draufschauen.

**Comment by dangoerr** [comment]
> Habe einen weiteren Datensatz mit fhelerhafter Anezige der Zuschreibung gefunden. In diesem Falle fehlt der Pfeil zum aufklappen und anzeigen der Quellen. ![fehlerhafte Anzeige Zuschreibung - keine Quellenangaben aufklappbar](https://private-user-images.githubusercontent.com/153098069/303042297-c737650e-740a-4078-9e04-de07896ea3fb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTIzNTcsIm5iZiI6MTcwOTExMjA1NywicGF0aCI6Ii8xNTMwOTgwNjkvMzAzMDQyMjk3LWM3Mzc2NTBlLTc0MGEtNDA3OC05ZTA0LWRlMDc4OTZlYTNmYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwOTIwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWI4Mzg0YjFjZTRmN2JjMjAwNTk3NDBjNTU5MzZhZTM3MDliNjFkYTljMmJmNmJmYzBiY2E2NDliYjliOTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.slwvenPfpSUl-LMywvzxUTHYackWM975z4cRkscsLe4)

Bei dem ist fehlt datenbankseitig schlicht der Quelleneintrag für "Lucas Cranach the Elder (and workshop)". Beim zweiten Eintrag "Lucas Cranach the Younger" gibt es einen Quelleneintrag, der lautet "Lucas Cranach der Jüngere als Werkstattmitarbeiter des Vaters (D. Koepplin 1974)", hat also keine eckige Klammer. Kann das relevant sein?

**Comment by cdaJana** [comment]
Bei dem Christus am Ölberg PRIVATE_NONE-P605 ging es in erster Linie darum, Teilinformationen, die im zugeklappten Zustand angezeigt werden (nämlich Lucas Cranach der Jüngere), in aufgeklapptem Zustand der Zuschreibung plötzlich verschwunden sind.
Zudem habe ich den Inhalt des Datensatzes inzwischen überarbeitet (unbekannt stand zuvor nicht im Suffix) und die Zuschreibung zu Cranach dJ in Werkstatt Cranach dJ geändert. 
Inzwischen ist im internen Bereich die Zuschreibung korrekt angezeigt.

**Comment by cdaJana** [comment]
Bei dem 2. Datensatz AT_KHM_GG3567 geht es darum, dass schlicht der Pfeil zum Aufklappen der Zuschreibungen fehlt.. Das hat ja nichts mit dem Dateninhalt zu tun.

**Comment by cdaJana** [comment]
AT_KHM_GG3567 hat jetzt bei der ersten Zuschreibung eine Quellenangabe, solte also mit dem nächsten Export korrekt angezeigt werden

**Comment by cdaJana** [comment]
Beide Datensätze werden im internen Bereich jetzt korrekt angezeigt. Issue kann also geschlossen werden :-)

**Comment by CranacharchivGunnar** [comment]
... und noch ein Issue erledigt! Super!
