### ISSUE TITLE
Verlinkung "Literatur anzeigen" funktioniert nicht

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#116]
### URL of the buggy page?

https://lucascranach.org/de

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Auf der Objektebene der Gemälde unter "Quellen / Publikationen" gibt es ja die Literatureinträge. Bei jedem dieser Einträge steht am Ende "Literatur anzeigen". Hier sollte auf den entsprechenden Eintrag in der Literaturdatenbank verlinkt werden. Dieser Link funktioniert derzeitig nicht. Bei mir wird angezeigt: "Diese Seite konnte nicht gefunden werden."

### On what kind of device does the bug appear?

Laptop

### What browsers are you seeing the problem on?

Firefox

**Comment by cnoss** [comment]
@yannic-bruegger wie sieht es hier aus?

**Comment by yannic-bruegger** [comment]
Fix ist unterwegs :)

**Comment by yannic-bruegger** [comment]
Hallo zusammen, ich habe die neue Version einmal im internen Bereich veröffentlicht. Könntet ihr einmal testen? Wenn ihr grünes licht gebt, werde ich es veröffentlichen. Danke! :)

@cnoss ich habe dir mal den PR gegeben
@CranacharchivGunnar prüfst du einmal ob es klappt?

https://lucascranach.org/intern/artefacts/
bzw.
https://lucascranach.org/de/intern/search-internal-preview
