### ISSUE TITLE
GitHub Projects-Link invalid

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#119]
### URL of the buggy page?

https://github.com/orgs/lucascranach/projects/2

### Contact Details

dg

### What happened?

Der Link auf der Startseite des internen Bereich (https://lucascranach.org/intern/) zur neuen GitHub Projects-Anzeige führt bei mir zu einem 404-Fehler.

**Comment by cnoss** [comment]
@dangoerr  das passiert wenn Du bei GitHub nicht eingeloggt bist … bitte mal einloggen und noch mal probieren und bescheid sagen

**Comment by dangoerr** [comment]
![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/f3c89c0d-4f2d-46f0-98f2-10fda1627556)

Klapt trotzdem nicht oder was mache ich falsch?

**Comment by dangoerr** [comment]
@yannic-bruegger Habe gerade in Slack gelesen...klappt jetzt. Danke

**Comment by yannic-bruegger** [comment]
Soweit klappt es jetzt bei folgenden Personen:


![Image](https://github.com/lucascranach/cda-orga/assets/36576062/24e64c75-28e8-41bc-b35d-6bfe4cda5d13)

Ich muss noch prüfen, ob wir mehr Menschen hinzufügen dürfen. Ich will keine unangemeldeten Lizenzkosten verursachen.

**Comment by yannic-bruegger** [comment]
Werde ich morgen im weekly ansprechen und dann auch relativ kurzfristig schließen.

**Comment by CranacharchivGunnar** [comment]
Die Liste mit der Prio-Reihenfolge enthält weniger Einträge als hier die offenen Issues (19).
Lassen sich diese automatisch in die Liste Prio-Reihenfolge einlesen?

**Comment by CranacharchivGunnar** [comment]
Sorry, zu schnell geschrieben: Die Prio Liste enthält mehr Issues (auch Eure aus cranach-search) als die Einträge hier und ein Issue "Add Mamoto analytics to search" soll vermutlich dem Eintrag "Niedrigere Zugriffszahlen..." Abhilfe schaffen....

https://github.com/lucascranach/cranach-search/issues/85
kann auch geschlossen werden. Da haben wir keine Zugriffsrechte

**Comment by yannic-bruegger** [comment]
Danke dir, für's Priorisieren! Wir haben an einigen Stellen ein paar Berechtigungsprobleme gehabt, weil ihr nicht Teil der Organisation wart. Ich habe euch dreien eine Einladung gesendet, womit ihr mehr Berechtigungen bekommt. Dann sollte die Zusammenarbeit hier etwas leichter gehen.

![Image](https://github.com/lucascranach/cda-orga/assets/36576062/3e547960-220e-4a29-b6f0-176aa528aba2)

Fehlt noch wer?

**Comment by cdaJana** [comment]
Danke fürs an Bord holen zu den erweiterten Berechtigungen bei Github.
Prinzipiell gehören noch Helen und Thomas zum Team.
Mit Helen habe ich gerade gesprochen. Sie benötigt keine Einladung und überlässt die Issues gern Gunnar, Daniel und mir.
Könnte mir vorstellen, dass Thomas das ähnlich sieht, werde ihn aber diesbezüglich noch fragen.
________________________________
Von: Yannic Brügger ***@***.***>
Gesendet: Mittwoch, 28. Februar 2024 10:07
An: lucascranach/cda-orga ***@***.***>
Cc: Herrschaft, Jana ***@***.***>; Comment ***@***.***>
Betreff: Re: [lucascranach/cda-orga] GitHub Projects-Link invalid (Issue #119)


Danke dir, für's Priorisieren! Wir haben an einigen Stellen ein paar Berechtigungsprobleme gehabt, weil ihr nicht Teil der Organisation wart. Ich habe euch dreien eine Einladung gesendet, womit ihr mehr Berechtigungen bekommt. Dann sollte die Zusammenarbeit hier etwas leichter gehen.

image.png (view on web)<https://github.com/lucascranach/cda-orga/assets/36576062/3e547960-220e-4a29-b6f0-176aa528aba2>

Fehlt noch wer?
