### ISSUE TITLE
Datierung in Werknormdaten

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#12]
Feld Datierung:
Hinter dem Datum den Eintrag aus dem Feld Kommentar einfügen, z.B. [cda, 2019]
(mit Pfeil zum Ausklappen) zudem hier Eintrag aus historische Daten und Kommentarfeld  einfügen

**Comment by jhfpereira** [comment]
Erster Stand:

Vorher:
![Bildschirmfoto 2020-03-15 um 22 46 51](https://user-images.githubusercontent.com/1864692/76711287-ee186280-670e-11ea-9244-559bf4f04308.png)

Nachher:
![Bildschirmfoto 2020-03-15 um 22 46 30](https://user-images.githubusercontent.com/1864692/76711290-f5d80700-670e-11ea-9446-81a7538e8f2b.png)


Zu klären ist, wie die Ausgabe der historischen Daten genau auszusehen hat.
