### ISSUE TITLE
Link zur CDA Startseite von Literaturseite

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#122]
Man kommt jetzt gelegentlich von der Google Suche direkt in die Literaturanzeige. Kannst Du bitte vor dem Backlink auch das "cda" mit Link zur Startseite einfügen

Bug kam von Gunnar via Mail

**Comment by yannic-bruegger** [comment]
Wenn ich mich richtig erinnere, haben wir das letzte Woche veröffentlicht, oder?



![Image](https://github.com/lucascranach/cda-orga/assets/36576062/a4c9b64a-7c19-47bf-b69e-8bd285904f71)

Dann würde ich das Issue entsprechend schließen.

**Comment by yannic-bruegger** [comment]
Ich werde das morgen im Weekly ansprechend udn dann entsprechend schließen.

**Comment by CranacharchivGunnar** [comment]
Ja, das funktioniert jetzt gut. Danke Euch. Kann geschlossen werden.
