### ISSUE TITLE
Keine Schreibrechte im Importer-Repository zum Ändern der Filter

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#129]
### URL of the buggy page?

https://github.com/lucascranach/importer/tree/edit-filter

### Contact Details

DG

### What happened?

Hi Yannic, habe versucht eine Korrektur an den Filtern im Importer-Repository einzupflegen, habe jedoch noch keine Schreibrechte und kann daher auch keinen neuen Branch anlegen. Habe daher erst einmal im schon vorhandenen Beispielbranch von Dir ("edit-filter") die Änderung vorgenommen, kann es aber auch nicht commiten:
![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/5a1b7841-1fcc-41d8-8d21-2eee82bacdb8)

**Comment by dangoerr** [comment]
FYI: Habe jetzt auf Markus' Rat hin das Repository "geforkt" und konnte nun Änderungen vornehmen.

**Comment by yannic-bruegger** [comment]
Hi, sorry. Die Berechtigungsstrukturen hier sind noch etwas wirr. 
Ich habe dir jetzt Berechtigungen gegeben. Sollte ab dem nächsten Mal also direkt funktionieren.

**Comment by dangoerr** [comment]
Danke, ich mache dann zukünftig meine Änderung im Branch "edit-filter" wie Du im Video erklärt hast. 
Die letzte Änderung habe ich ja in der geforkten Fassung gemacht, die Pull Request liegen Dir und Christian ja vor.
