### ISSUE TITLE
Klassifikation in Werknormdaten

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#13]
Klassifikation: Druckgrafik
Hier direkt hinter „Druckgrafik“ den Eintrag aus dem Feld „Objektname“ einfügen, d.h.:
„Klassifikation: Druckgrafik, Holzschnitt“

Weiter unten entfallen dafür „Objekname: Holzschnitt“

**Comment by jhfpereira** [comment]
Aktueller Stand
![classification_with_objectname](https://user-images.githubusercontent.com/1864692/75637260-ac26f100-5c25-11ea-8147-f5633292f90b.png)
