### ISSUE TITLE
Anpassung der Institutionen im Filter der Archivalien

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#130]
### URL of the buggy page?

https://lucascranach.org/de/search?page=1&kind=archivals

### Contact Details

DG

### What happened?

Bevor der aktuelle Import live gehen kann, müssten auch bei den Archivalien die Institutionen im Filter angepasst werden. Kann ich das wie bei den Filtern der Gemälde tun und wenn ja, in welchem Verzeichnis?
![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/01ab74d0-a70e-4844-9563-7e19c74803d3)

**Comment by yannic-bruegger** [comment]
Sind durch Elastic-Search automatisch da :)
