### ISSUE TITLE
neuer Datenimport

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#135]
### Contact Details

gunnar.heydenreich@th-koeln.de

### What is your name and adress?

Gunnar

### Your contribution

1. Von zwei Gemälden werden die Abbildungen aktuell noch nicht angezeigt:
https://lucascranach.org/intern/artefacts/de/PRIVATE_NONE-P612/
https://lucascranach.org/intern/artefacts/de/DE_SMG-Lost_Ahv343/

2. Abb. der Archivalien fehlen noch.

3. Hier werden die neuen (zu ersetzenden) Abb. noch nicht angezeigt:
https://lucascranach.org/intern/artefacts/de/DE_SKMT-Lost_L-VI-1g40/
https://lucascranach.org/intern/artefacts/de/PRIVATE_NONE-P193/
 
4. Die pdf Dokumente werden alle noch nicht angezeigt:
z.B. CH_PTSS-MAS_A652_FR-none_1936_Document.pdf
AU_NGV_4700-3_FR-none_1998_analysis-report
PRIVATE_NONE-P603_FR-none_[2007-05-06](tel:20070506)_Report-002

**Comment by cnoss** [comment]
## PRIVATE_NONE-P612
![image](https://github.com/lucascranach/cda-orga/assets/2807738/a0f04dc9-446e-484b-9063-16c7a71872c9)

Ordner heißt: PRIVATE_NONE-P612_FR-none müsste nach meinem Verständnis aber PRIVATE_NONE-P612_FR408C heißen, oder liege ich falsch?

**Comment by cnoss** [comment]
## DE_SMG-Lost_Ahv343

![image](https://github.com/lucascranach/cda-orga/assets/2807738/57862548-e3d2-4b30-9738-12f9e532dec0)

Hier fehlt das _Overall Suffix.

**Comment by cnoss** [comment]
## PRIVATE_NONE-P193

Fehler erkannt … werde ich asap korrigieren.

**Comment by cnoss** [comment]
Mit den Archivalien kämpfe ich noch 🤫. Die Documents hab ich mir noch nicht angeschaut.

**Comment by CranacharchivGunnar** [comment]
Du liegst ganz richtig:
- Ordner und Abb. "PRIVATE_NONE-P612_FR-none" müssen richtig heißen "PRIVATE_NONE-P612_FR408C" 
Die Erkenntnis, dass es FR408C ist, kam erst nachdem ich die ID bereits kopiert hatte.

- DE_SMG-Lost_Ahv343 
Hab ich geschlampt. Kannst Du das Suffix "_Overall" bitte in den Dateinamen am Ende einfügen?

- DE_SKMT-Lost_L-VI-1g40. Ist magisch gelöst, jetzt wird das Vorschaubild in der Übersicht korrekt angezeigt.

Hoffe pdfs und Archivalien machen keine größeren Probleme.
Wir sind mit den Korrekturen, Sortierreihenfolge etc. fast durch, so dass wir in der nächsten Woche den finalen Export für die Online-Freischaltung planen könnten.

Herzlich,
g

**Comment by CranacharchivGunnar** [comment]
Hi Christian,
- die Abb. der Gemälde sind jetzt alle Abb. da. Completed! Super!

- Bei den Archivalien werden nicht alle angezeigt. Es fehlen z.B. noch die Abb. bei:
https://lucascranach.org/intern/artefacts/de/DE_BStAN_Briefbuecher_Bd61_231/
https://lucascranach.org/intern/artefacts/de/DE_BStAN_Briefbuecher_Bd61_245/
https://lucascranach.org/intern/artefacts/de/DE_BStAN_Briefbuecher_Bd62_143r-144r/
https://lucascranach.org/intern/artefacts/de/DE_StSWR_147_Bc107_26-27/
https://lucascranach.org/intern/artefacts/de/DE_StSWR_147_Bc107_35-36/
https://lucascranach.org/intern/artefacts/de/DE_StSWR_144_Bc108_27v-29r/
https://lucascranach.org/intern/artefacts/de/DE_StSWR_144_Bc108_117r-118r/

- die pdfs sind zum Teil jetzt doppelt da: Muss nochmal schauen, wie oft/wo das der Fall ist.

**Comment by CranacharchivGunnar** [comment]
08_Conservation ist richtig

**Comment by CranacharchivGunnar** [comment]
Sieht sehr gut aus, soweit ich erkennen kann, sind alle Bilder, alle Inhalte angekommen...
Mille Grazie!
