### ISSUE TITLE
Anzeige der Bilddateien in einem Archivalien-Datensatz noch ungeordnet (dringend, kann aber nach Freischaltung geschehen)

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#136]
Die Bilddateien innerhalb eines Archivalien-Datensatz werden bisher noch ungeordnet angezeigt, müssen aber geordnet nach Seitenzahlen erscheinen, um die Transkription nachverfolgen zu können.

Regel für die Sortierung nach Dateinamen:
1. Sortierung aufsteigend nach der ersten Zahl (nicht Ziffer) nach dem letzten Unterstrich des Dateinamens
2. Wenn Zahl bei zwei Dateinamen identisch, Suffix r vor Suffix v der Zahl, Suffix muss aber nicht zwingend vorhanden sein

Das würde auf jeden Fall schon einmal eine grobe Ordnung ergeben, ob es alle Sonderfälle abgedeckt, müsste ich danach mal checken und ggf. die Regel um weitere Punkte ergänzen.

**Comment by yannic-bruegger** [comment]
@markusalterauge schaut einmal nach, ob die Dtaen in den JSONS bereits sortiert sind

**Comment by markusalterauge** [comment]
Am Beispiel https://lucascranach.org/de/DE_ThHStAW_EGA_Reg-Bb_2746_31v_49r/ findet sich in den Daten das Array scanNames in dem alles sortiert drinnen liegt. 
`"scanNames": [
                "DE_ThHStAW_EGA_Reg-Bb_2746_31v",
                "DE_ThHStAW_EGA_Reg-Bb_2746_33v_34r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_36r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_36v_37r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_37v_38r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_38v_39r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_39v_40r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_40v_41r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_41v_42r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_42v_43r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_43v_44r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_44v_45r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_45v_46r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_46v_47r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_47v_48r",
                "DE_ThHStAW_EGA_Reg-Bb_2746_48v_49r"
            ]`

**Comment by markusalterauge** [comment]
inventoryNumber DE_ThHStAW_EGA_Reg-Pp_355_8_1r_99v hat sehr viele Scans und ist ebenfalls sortiert. Meine Annahme ist, dass das bei allen Daten im Datensatz so sein sollte.

**Comment by dangoerr** [comment]
Ja, alle sollten sortiert sein. Die Reihenfolge der Sortierung wird von mir auch händisch angegeben. Für DE_ThHStAW_EGA_Reg-Bb_2746_31v_49r müsstest Du z. B. ein Feld finden, in dem folgende Angaben stehen:
DE_ThHStAW_EGA_Reg-Bb_2746_31v
#DE_ThHStAW_EGA_Reg-Bb_2746_33v_34r
#DE_ThHStAW_EGA_Reg-Bb_2746_36r
#DE_ThHStAW_EGA_Reg-Bb_2746_36v_37r
#DE_ThHStAW_EGA_Reg-Bb_2746_37v_38r
#DE_ThHStAW_EGA_Reg-Bb_2746_38v_39r
#DE_ThHStAW_EGA_Reg-Bb_2746_39v_40r
#DE_ThHStAW_EGA_Reg-Bb_2746_40v_41r
#DE_ThHStAW_EGA_Reg-Bb_2746_41v_42r
#DE_ThHStAW_EGA_Reg-Bb_2746_42v_43r
#DE_ThHStAW_EGA_Reg-Bb_2746_43v_44r
#DE_ThHStAW_EGA_Reg-Bb_2746_44v_45r
#DE_ThHStAW_EGA_Reg-Bb_2746_45v_46r
#DE_ThHStAW_EGA_Reg-Bb_2746_46v_47r
#DE_ThHStAW_EGA_Reg-Bb_2746_47v_48r
#DE_ThHStAW_EGA_Reg-Bb_2746_48v_49r

Sollten diese Informatione nicht nutzbar sein (Christian hatte etwas in diese Richtung angedeutet), gilt die Sortierregel wie oben angegeben.

**Comment by dangoerr** [comment]
Habe jetzt mal einige Stichproben durchgeführt. Es scheint so, dass bei den alten Einträgen von 2017 oder früher die Abweichungen da sind, bei den neueren schon.

Schau mal bitte, ob die Sortierung bei DE_BStAN_Briefbuecher_Bd61_238v-240r funktioniert, da sollte es matchen. Wenn es funktioniert, muss ich wohl mal durch TMS gehen und alles auf einen einheitlichen, zumindest aber auf den gleichen Stand bringen.

**Comment by cnoss** [comment]
@dangoerr das sieht deutlich besser aus. Wie wollen wir weiter machen? Ihr müsstet erst die Fehler aus den ScanNames im TMS entfernen, oder? Wann würdet ihr das schaffen?

@cnoss ist im Branch m-sorted-archivals

**Comment by dangoerr** [comment]
Puh, das muss ich mich erst noch einmal reindenken...ich müsste nun die Archivalien in TMs durchschauen und sicher gehen, dass die Angaben in ScanNames immer mit den Dateinamen übereinstimmt. Habe ich richtig in Erinnerung, dass die Angaben in ScanNames immer aus der vollständigen TMS-Object-ID + der SPezifizierung des individuellen Scans bestehen muss. Andersnfalls wäre es doch auch eine Option, die Dateinamen an den TMS-Eintrag anzupassen (dann wäre zumindest kein Export notwendig, damit die Änderung wirksam wird).

**Comment by cnoss** [comment]
Hi, da bin ich überfragt – der String in ScanNames muss auf jeden Fall mit dem Dateinamen übereinstimmen, bzw. darin enthalten sein und nur eine Datei adressieren. @dangoerr wenn ich was tun kann: bitte melden.

**Comment by dangoerr** [comment]
Ok, ich bin nächste Woche im Urlaub, melde mich danach aber sobald ich durch bin.

**Comment by dangoerr** [comment]
Bin gerade dabei, das zu bearbeiten und vergleiche die Dateinamen im Serverordner /home/mkpacc/originals/archivals mit den Angaben im passenden TMS-Feld ScanNames. Kann es sein, dass der Ordner auf dem Server nicht aktuell ist? Ich finde zunehmend TMS-Datensätze zu denen es keine Abb. in dem Ordner auf dem Server gibt, die aber in der Live-Version der Datenbank fehlerfrei angezeigt werden.
Hier ein paar Beispiele:
DE_BStAN_Briefbuecher_Bd62_143r-144r_143r
#DE_BStAN_Briefbuecher_Bd62_143r-144r_143v
#DE_BStAN_Briefbuecher_Bd62_143r-144r_144r

DE_StSWR_113_Bc101_359-383_359-383r
#DE_StSWR_113_Bc101_359-383_359-383v

DE_StSWR_144_Bc108_27v-29r_27v-28r
#DE_StSWR_144_Bc108_27v-29r_28v-29r

DE_StSWR_144_Bc108_117r-118r_117r
#DE_StSWR_144_Bc108_117r-118r_117v-118r

Bevor ich weitermache, müssten wir erst einmal klären, ob ich ScanNames gerade überhaupt auf den korrekten Stand bringe, da die Serverangaben in TMS übernehme.
