### ISSUE TITLE
Reihenfolge der Daten bei den Werknormdaten

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#14]
Reihenfolge der Anzeige ändern:
- CDA ID
- Permalink (noch eingügen)
- Hollstein
- Bartsch 
- GND Nr. (noch einfügen)
werden weiter unten nach Signatur/Datierung angezeigt

**Comment by jhfpereira** [comment]
Aktueller Stand
![reorder_fields](https://user-images.githubusercontent.com/1864692/75638064-a1228f80-5c2a-11ea-8e19-0fd3b496b1f7.png)
