### ISSUE TITLE
[Functional Bug]: Overall_overview Abbildung doppelt angezeigt - bitte 1 x löschen

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#144]
### URL of the buggy page?

https://lucascranach.org/de/search/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Hi,
bei einigen Werken wird aktuell die Overall_overview Abb. doppelt angezeigt, 1 x oben (korrekt) und 1 x unten (unter Restaurierung). Unten zudem in größerer Größe, das finde ich irritierend, da dauerhaft präsent (ausgeklappt) und nicht wirklich hilfreich. Schlage vor, die Abbildungen Overall_overview unten zu löschen.
Herzlich,
Gunnar
![grafik](https://github.com/user-attachments/assets/2878085b-5312-4e61-b325-2673db184e53)

**Comment by CranacharchivGunnar** [comment]
Hi Christian,
sorry, mache den Fall nochmal auf. Sowohl im internen als auch im öffentlichen Bereich sehe ich die zweite overall-overview Abbildung immer noch genau so, wie oben im Screenshot, auch nachdem ich den Cache gelöscht habe.
Herzlich,
G

**Comment by cnoss** [comment]
@CranacharchivGunnar  ja. Die Deplyment Pipeline war leider kaputt, daher wurden die Dateien nicht ausgespielt. Bitte noch mal prüfen und dann den Bug im besten Fall schließen. Viel Spaß in Norwegen!

**Comment by CranacharchivGunnar** [comment]
Thanks, completed!
