### ISSUE TITLE
Anpassung Cranach-Artefacts references Komponente

### ISSUE THREAD

**Issue by markusalterauge** [lucascranach/cda-orga#148]
Hier muss die references Komponente angepasst werden, um die neue Datenstruktur der JSON Dateien nutzen zu können.

Referenzen sehen z.B. so aus:

references = {
  onSameSheet = [],
  identicalWatermark = [],
  partOfWorks = [],
  relatedWorks = []
}

**Comment by cnoss** [comment]
Mit dem letzten Update wurde das im internen Branch integriert:
https://github.com/lucascranach/cranach-artefacts/pull/54

Gleiches gilt für den Preview Branch:
https://github.com/lucascranach/cranach-artefacts/pull/51
