### ISSUE TITLE
[Functional Bug]: typo in beschreibung

### ISSUE THREAD

**Issue by calvinhnzr** [lucascranach/cda-orga#153]
### URL of the buggy page?

https://lucascranach.org/de/DE_WRMK_WRM3207

### Contact Details

-

### What happened?

Zweiter Satz in der Beschreibung:

"...Den **Koüpf** leicht nach links geneigt..."
statt
"...Den **Kopf** leicht nach links geneigt..."

**Comment by dangoerr** [comment]
Danke, habe den Fehler in TMS geändert, wird also mit dem nächsten Export behoben.
