### ISSUE TITLE
Film in redaktionellen Bereich integrieren

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#154]

**Comment by cnoss** [comment]
@dangoerr @CranacharchivGunnar ich hab den Film jetzt ja bei Vimeo und könnte den mal im redaktionellen Bereich einbinden … wo soll der da hin?

**Comment by CranacharchivGunnar** [comment]
Mein spontaner Vorschlag wäre, auf der Startseite das Tumbnail Bild mit den blauen Kupferstreifen links neben dem Menüpunkt "Forschung" mit dem Video zu ersetzen. Da würde es inhaltlich auch gut hinpassen. Hast Du einen besseren Vorschlag?

![Forschung](https://github.com/user-attachments/assets/b16e5e02-8b43-44f7-a231-9744126f5241)

**Comment by dangoerr** [comment]
Das klingt doch gut. Lass' doch mal schauen, wie er da aussieht...

**Comment by cnoss** [comment]
@dangoerr @CranacharchivGunnar 
Dafür gibt es leider keinen Layoutblock … hab es jetzt mal stumpf drunter geklebt. Ich könnte den Forschungstext drunter schreiben:

![Image](https://github.com/user-attachments/assets/3c5439ed-fe32-47a0-a3af-2d7972e20abb)

**Comment by CranacharchivGunnar** [comment]
Schade, aktuell erscheint mir tatsächlich der Entwurf etwas schwergewichtig und überdimensioniert.
Wäre es möglich den Film in die rechte Spalte ganz nach unten zu setzen (unter "Newsletter"). Da ist in meiner Ansicht gerade noch ein entsprechender "grauer" Platz frei und es erschiene mir zusammen mit dem anderen Video ganz oben in der rechten Spalte auch logisch verortet.

![grafik](https://github.com/user-attachments/assets/d95bb900-fe5e-49aa-94c1-00cc590e517b)

**Comment by CranacharchivGunnar** [comment]
Hi,
auch nicht optimal, aber eine Möglichkeit, bis die Seite wieder voll editierbar ist. Dann können wir ja nochmal schauen, ob es sich weiter optimieren lässt - in diesem Sinne ist auch Daniels Meinung.
Also, gern so, vielen Dank!
Herzlich,
Gunnar

**Comment by CranacharchivGunnar** [comment]
Läuft, sehr schön!
Die Anordung können wir wohl noch weiter optimieren, sobald Daniel wieder Zugriff hat.
Danke Dir!
