### ISSUE TITLE
Zoom Funktion

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#16]
Wenn dieser in neuem Tab geöffnet wird, wird die zoom Funktion nicht mehr angezeigt.

**Comment by jhfpereira** [comment]
Bug wurde mit Commit https://github.com/lucascranach/cranach-grafiken-gatsby/commit/c69499774296f8a5d888cd88cfeaa04d3d3ec990 behoben.
Konnte leider nur in Builds reproduziert werden, wodurch das Debugging etwas aufwendiger wurde.
