### ISSUE TITLE
Fehlerhafte Darstellung des Standortes "Heerenberg, ’s-"

### ISSUE THREAD

**Issue by calvinhnzr** [lucascranach/cda-orga#162]
Aktuell werden Werke aus dem gleichnamigen Standort mit "Heerenberg, ’s-" gekennzeichnet.
Die Korrekte Schreibweise wäre "s-Heerenberg". 

e.g.
https://lucascranach.org/de/AT_BSM_NONE-001

**Comment by calvinhnzr** [comment]
Könnt ihr mal nachschauen, ob das eventuell ein Editor Fehler ist. Ansonsten könnte es vllt am Import oder Parsen liegen.

**Comment by dangoerr** [comment]
Habe die korrekte Schreibweise im Thesaurus gefunden und geändert. Mit dem nächsten Export Anfang Dezember sollte es da also auch wieder passen.
