### ISSUE TITLE
Unterschiede bei der Bennenung des Standortes "Den Haag"

### ISSUE THREAD

**Issue by calvinhnzr** [lucascranach/cda-orga#163]
Folgendes Werk hat den Standort "Haag" 
https://lucascranach.org/de/NL_RM_SK-A-2561

Sollte der Standort wie bei den folgenden Werken zu "Den Haag" angeglichen werden muss?
https://lucascranach.org/de/NL_Mh_917
https://lucascranach.org/de/NL_Mh_890

**Comment by dangoerr** [comment]
Ja, bei [NL_RM_SK-A-2561](https://lucascranach.org/de/NL_RM_SK-A-2561) war der falsche Ort eingetragen, habe ich in TMS geändert, Inzwischen gibt es ja eine neue TMS-Version mit  einem aktualisierten geographischen Thesaurus. [NL_RM_SK-A-2561](https://lucascranach.org/de/NL_RM_SK-A-2561) ist somit nach dem neuen eingetragen, die anderen beiden nach dem alten. Vielleicht gute Testobjekte, um zu prüfen, dass beide Thesauri die gleichen Informationen ausgeben?
