### ISSUE TITLE
Felder Hollstein und Bartsch Nr.

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#17]
Hier keine Felder und Einträge Hollstein und keine Bartsch Nr. anzeigen (erfolgt im Moment uneinheitlich z.B. bei Christophorus)

**Comment by jhfpereira** [comment]
Sowohl für das virtuelle als auch die realen Objekte?

Sollten sie nicht zudem irgendwo weiter nach unten wandern bzw. irgendwo hinter einem Klick "versteckt" sein?

**Comment by jhfpereira** [comment]
Wie hängt dies mit dem Issue https://github.com/lucascranach/cda-orga/issues/14 zusammen?

**Comment by jhfpereira** [comment]
Gerade erst am Label erkannt, dass es sich auf die Abzüge bezieht.

**Comment by jhfpereira** [comment]
Vorheriger Stand:

![Bildschirmfoto 2020-03-15 um 19 22 13](https://user-images.githubusercontent.com/1864692/76707758-56a51680-66f2-11ea-9ce5-2e6f086ebefe.png)


Aktueller Stand:

![Bildschirmfoto 2020-03-15 um 19 17 34](https://user-images.githubusercontent.com/1864692/76707734-19408900-66f2-11ea-86a1-2abe0c1da04a.png)
