### ISSUE TITLE
Felder anpassen

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#18]
Objektname Holzschnitt nicht anzeigen
Klassifikation „Druckgrafik“ nicht anzeigen, aber 1. Zustand, das feld bekommt den Namen Druckzustand, Version:

**Comment by jhfpereira** [comment]
Vorher
![vorher_klassifikation](https://user-images.githubusercontent.com/1864692/75634805-ffdb0f80-5c10-11ea-93c6-506da8251153.png)

Nachher
![nachher_klassifikation](https://user-images.githubusercontent.com/1864692/75634808-023d6980-5c11-11ea-8016-9f2a23fc41ac.png)
