### ISSUE TITLE
Umbrüche in Mengentexten 

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#24]
Die müssen wieder rein, z.B. bei den Maßen

**Comment by jhfpereira** [comment]
NewLine-Zeichen werden unverändert aus den XMLs übernommen und landen unverändert in den JSONs.
Hier sollte man für das Lösen des Problems schon mal eher nicht ansetzen.

Denke es bietet sich an, die Umbrüche möglichst recht spät in der "Kette" und möglichst vor der direkten Ausgabe zu behandeln.
Damit es mit React klappt, muss ein String mit NewLine-Zeichen erst anhand von `\n` aufgetrennt werden.
Nach jedem Array-Feld (außer dem letzten) muss dann ein `<br />`-Element eingefügt werden (jsx).


Felder in denen NewLine-Zeichen gefunden wurden (20201009) und für deren Werte der zuvor beschriebene Ablauf angewandt werden muss:

titles[].title
description
signature
dating.dated
dimensions
medium
inscription
provenance
markings
exhibitionHistory
relatedWorks
restorationSurveys[].tests[].text
restorationSurveys[].overallAnalysis
additionalTextInformation[].text

**Comment by jhfpereira** [comment]
Gerade nochmal über die CopyText-Atom-Komponente gestoßen.
Das Wrappen der aufgetrennten Texte in `p`-Elemente geht natürlich auch :)

**Comment by cnoss** [comment]
wrappen in <p> wäre natürlich schöner … ich bau das mal ein
