### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#25]
Noch mal die Frage: können wir Hyperlinks automatisiert klickbar machen.

**Comment by jhfpereira** [comment]
Damit zusammenhängendes Issue:

https://github.com/lucascranach/cranach-grafiken-gatsby/issues/14


@cnoss 
Habe meine Nachricht an Dich bezüglich der Probleme bei URL-Extraktion vom 14. August wiedergefunden (Slack).

> [...] das Extrahieren von URLs aus Texten leider recht schwierig und eher stark fehleranfällig wird.
Wie wir schon festgestellt haben, sind URLs in verschiedenen Arten vorzufinden.
Mal in eckigen Klammern, mal nach einem Doppelpunkt und mal auch mit Metainfos (z.B. accessed).
Hingegen ist das Finden von Texten mit einer URL schon mal leichter, da man recht gut nach “http” regexen kann (wobei es in den Texten eine URL ohne Protokollangabe, aber mit “www”-Subdomain existiert). Schwierig wird es mit URLs, die weder Protokoll noch “www”-Subdomain aufweisen. Generell ist das Problem aber halt die Extraktion, was nicht so gut klappen wird.
Haben leider Fälle, wo eine URL per eckige Klammern ausgezeichnet ist, aber die URL selbst eckige Klammern im Pfad-Bereich aufweist. Da kommt man mit RegExp nicht weiter. Das müsste man eher parsen.
Und dann stellt sich dann auch die Frage, wie man die Grafik-Datenstruktur so erweitert, dass man extrahierte URLs irgendwie unterbringt, da eine URL in verschiedenen Freitextwerten auftauchen kann.

Bezüglich eckige Klammern in Pfaden: Vllt. sollten URLs auch explizit mit enkodierten Entities hinterlegt werden, da wir so oder so früher oder später mit der Markdown-Syntax für das Auszeichnen von Links in Probleme laufen. Konkret die Verwendung von runden Klammern, die weder encoded noch escaped sind.

Z. B. wie sowas:

\[Test\]\(http://test-url.com/step1/substep1/?q=test+(subtest)&order=asc)
