### ISSUE TITLE
Zusätzliches Views Übersichtsseite

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#3]
- zweite Ansicht mit kleineren Thumbs   
- dritte Ansicht als Listenansicht  (mit gehighlighteten Texten)

**Comment by jhfpereira** [comment]
@cnoss Gibt es für "mit gehighlighteten Texten" eine genaue Vorstellung?
Kann mir darunter nämlich nichts genaues vorstellen.

**Comment by jhfpereira** [comment]
Bisheriger View:
![artefact-overview-card](https://user-images.githubusercontent.com/1864692/79697741-ad1eeb00-8284-11ea-94bc-ca5e9234437e.jpg)

Zweite Ansicht mit kleineren Thumbs:
![artefact-overview-card-small](https://user-images.githubusercontent.com/1864692/79697755-be67f780-8284-11ea-869f-c1831c192de2.jpg)

Dritte Ansicht als Listenansicht
![artefact-overview-list](https://user-images.githubusercontent.com/1864692/79697763-ce7fd700-8284-11ea-9a64-8f8869f4e065.jpg)
