### ISSUE TITLE
Filterung der Bildnisgruppen des KKL

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#30]
Um die Werke des KKL zukünftig in fünf Bildnisgruppen aufteilen zu können, haben wir alle Gemälde und alle Werknormdaten der Graphik mit einer „KKL-Ordnungsnummer“ versehen. Diese ist im TMS-Feld „Andere Nummern“ vermerkt. Das Feld ist bei den Gemälden bisher ungenutzt, bei den Graphiken bekommt ihr aber dort bereits die Hollstein- und Bartsch-Nummer her.
Hier ein Bsp.: 
![grafik](https://user-images.githubusercontent.com/91158095/137278964-14643f24-7e81-4b76-a29a-2d4f6e477447.png)

Die Ordnungnummer besteht immer aus einer römischen Zahl (I bis V für die Bildnisgruppe) gefolgt von einem Punkt (Marker für Euch), dem Buchstaben D, M oder Z (für Druckgraphik, Malerei oder Zeichnung) und einer laufenden arabischen Nummer. Die Bildnisgruppe I hat zudem noch sechs Untergruppen (I.1 bis I.6), die aber für Eure Sortierung nicht relevant sein werden. 
Die einzelnen Gruppen können also anhand der Zeichen, die vor dem Punkt in der Ordnungsnummer stehen, ausgelesen werden.

Die einzige Ausnahme bildet eine sechste Gruppe, der „Anhang zum KKL“. Hier wurden Werke aufgenommen, die wir untersucht haben und aufgrund der Ergebnisse aus dem Korpus des KKL aussortiert haben, etwa weil sie deutlich nach dem Untersuchungszeitraum 1519-30 entstanden sind.
Deren KKL-Ordnungsnummer baut sich ebenso auf, nur das nach dem Buchstaben für Druckgraphik, Malerei oder Zeichnung das Kürzel „-Sup“ (=Supplement) eingeschoben wird.
Bsp.:
![grafik](https://user-images.githubusercontent.com/91158095/137278997-86b770e3-a82c-4fa3-b9cb-057a83bc0ef8.png)

 
Alle Werke, die die Zeichenfolge „-Sup“ in der Ordnungsnummer haben, gehören also dieser sechsten Gruppe an und können daran herausgefiltert werden.

**Comment by cnoss** [comment]
URLs:
- ?language=de&sort_by=sorting_number.asc&catalog_name=KKL-Ordnungsnummer&catalog_work_reference_number:diff=I.*&entity_type:neq=DOCUMENT&size_height:gt=200&size=50
- ?language=de&sort_by=sorting_number.asc&catalog_name=KKL-Ordnungsnummer&catalog_work_reference_number:diff=II.*&entity_type:neq=DOCUMENT&size_height:gt=200&size=50
- ?language=de&sort_by=sorting_number.asc&catalog_name=KKL-Ordnungsnummer&catalog_work_reference_number:diff=III.*&entity_type:neq=DOCUMENT&size_height:gt=200&size=50
- ?language=de&sort_by=sorting_number.asc&catalog_name=KKL-Ordnungsnummer&catalog_work_reference_number:diff=IV.*&entity_type:neq=DOCUMENT&size_height:gt=200&size=50
- ?language=de&sort_by=sorting_number.asc&catalog_name=KKL-Ordnungsnummer&catalog_work_reference_number:diff=V.*&entity_type:neq=DOCUMENT&size_height:gt=200&size=50
- ?language=de&sort_by=sorting_number.asc&catalog_name=KKL-Ordnungsnummer&catalog_work_reference_number:diff=*.*&entity_type:neq=DOCUMENT&size_height:gt=200&size=50
