### ISSUE TITLE
Zwei Gemälde weiterhin an falscher Position

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#38]
### URL of the buggy page?

https://lucascranach.org/de/DE_SMF_1731/ und DE_HHK_NONE-HHK003

### Contact Details

dg

### What happened?

Die beiden Gemälde erscheinen an letzter Stelle im cda, was nicht der SortNumber entspricht.  Hier scheint die letzte Änderung noch nicht zu greifen...?

**Comment by cnoss** [comment]
@jhfpereira wir sollten die sortNumber und Year und Position als data Attribut an die artefact-card hängen, sonst können wir das sehr schlecht debuggen … könntest Du das machen?

**Comment by jhfpereira** [comment]
@cnoss Dazu habe ich gerade ein PR erstellt: https://github.com/lucascranach/cranach-search/pull/76

Das Problem hier ist aber, dass die beiden Objekte wohl saubere SortingNumbers haben. Mir ist aber nicht klar wieso diese nicht korrekt sortiert werden.

@vschaefer Könnte es vllt an irgendeinem (Bucket-, Sorting-)Limit liegen?

**Comment by cnoss** [comment]
Die beiden Objekte haben ein Dating-Beginn < 1500  … unsere Range startet aber bei 1500 … daher bekommen die einen recht schlechten Score und landen daher gaaaaanz hinten.
