### ISSUE TITLE
Bei Galerieansicht wird an einer Stelle falsches Feld abgefragt

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#39]
### URL of the buggy page?

https://lucascranach.org/de/DE_GNMN_Gm1570/

### Contact Details

dg

### What happened?

In einer der drei wählbaren Galerieansichten (siehe Screenshot) soll unter anderem Infos aus den Feldern Besitzer/Repository angezeigt werden. Aktuell scheint das aber die Felder Eigentümer/Owner zu sein.
Bei  markierten Bsp (https://lucascranach.org/de/DE_GNMN_Gm1570/) steht Merkelsche Familienstiftung (= Eigentümer), es sollte aber Germanisches Nationalmuseum dort stehen.
Ist bisher nicht aufgefallen, weil Besitzer und EIgentümer in den meisten Fällen identisch sind, aber eben nicht in allen.

### Additional context & Screenshots

![grafik](https://user-images.githubusercontent.com/91158095/169857962-50024747-ff01-4240-bb3d-c7fbea94325e.png)

**Comment by jhfpereira** [comment]
Ist angepasst und auf prod deployed.

![Bildschirmfoto 2022-06-10 um 17 12 32](https://user-images.githubusercontent.com/1864692/173096353-dfcf2296-e47c-4b3c-9d9a-1fa0284a89a6.png)
