### ISSUE TITLE
[IMPROVEMENT]: pdfs lassen sich nicht öffnen

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#40]
### Contact Details

gunnar.heydenreich@th-koeln.de

### What is your name and adress?

Gunnar

### Your contribution

Beim Datensatz
https://lucascranach.org/en/DE_SKD_GG1906A/
lassen sich pdfs unter
13.10.2010Technical examination / Scientific analysis
nicht öffnen
z.B. 
[DE_SKD_GG1906A_FR014_2010-10-13_IRR-Detail-002.pdf](https://lucascranach.org/documents/DE_SKD_GG1906A_FR014/03_IRR/DE_SKD_GG1906A_FR014_2010-10-13_IRR-Detail-002.pdf)

Es kommt die Meldung:
The requested URL /documents/DE_SKD_GG1906A_FR014/03_IRR/DE_SKD_GG1906A_FR014_2010-10-13_IRR-Detail-002.pdf was not found on this server.

... dies scheint mit zahlreichen pdfs der Fall zu sein. Müssen die noch umziehen?

**Comment by cnoss** [comment]
Jo, die PDF sehe ich im Ordner leider nicht: 
<img width="660" alt="image" src="https://user-images.githubusercontent.com/2807738/169875238-ad5037d5-0a09-4f57-9436-13a098572197.png">

**Comment by CranacharchivGunnar** [comment]
Danke für den schnellen Check! Richtig, ich habe soeben die Ordner aus dem Jahre 2012 durchgesucht und all die gesuchten pdfs auch nicht gefunden.
Vermutlich wurden diese in TMS angelegten Links in dem alten System gar nicht angezeigt, weil in den Ordnern keine pdfs dazu vorhanden??
Wir werden die Links in TMS löschen...
Erledigt!

**Comment by CranacharchivGunnar** [comment]
Hi Christian,
habe heute nochmal mit Helen geprüft und festgestellt, es müssten doch
mehr pdfs vorhanden sein (es handelt sich nicht nur um TMS Link-Einträge
zu denen es keine realen pdfs gibt).
Z.B. haben wir in 2012 foldende Dateien auf den Server kopiert: 

DE_SKD_GG1906A_FR014_2003-05-26_ExaminationReport-001

DE_SKD_GG1906A_FR014_2003-05-26_ExaminationReport-002
...
(siehe Anhang)


Frage: Sind diese Dateien noch irgendwo auf dem Server, oder sind sie
verloren gegangen? 

Dann müssten wir sie nochmals liefern...



Herzlich,
Gunnar





>>> Christian Noss ***@***.***> 23.05.22 19.31 Uhr >>>

 Jo, die PDF sehe ich im Ordner leider nicht:
 
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID:
***@***.***>
