### ISSUE TITLE
Wo landet Fehler-Feedback zu Werken?

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#43]
Frage: Wo landet die Nachricht, wenn uns jemand über die Feedbackfunktion auf einen Fehler aufmerksam macht?

Bisher wurden diese Nachrichten auf das E-mail Konto [cda-contact@kunstpalast.de](mailto:cda-contact@kunstpalast.de)
weitergeleitet, von wo aus wir beantwortet haben (meherere Zugriffsrechte...).
Lässt sich das wieder so mit einer Weiterleitung einrichten?

(Habe soeben mal einen Test gestartet und der kam dort auf dem E-mail Konto nicht an)

Herzlich,
Gunnar

**Comment by cnoss** [comment]
@CranacharchivGunnar  Ist jetzt eingerichtet.

**Comment by CranacharchivGunnar** [comment]
Sorry, aber ich finde die Meldungen weder auf Github noch in dem Email
Account.
Kannst Du mir bitte helfen, wo die Meldungen genau eingehen?

Habe soeben zum Test eine weitere Feedbackmeldung von FR001 auf den Weg
gegeben...
Herzlich,
Gunnar




>>> Christian Noss ***@***.***> 25.05.22 17.44 Uhr >>>

 Closed #43 as completed.
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID:
***@***.***>
