### ISSUE TITLE
KKL-Werke PRIVATE_NONE-P405 und DE_DHKW-MWMW_Z875 ohne Abbildungen

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#44]
### URL of the buggy page?

https://lucascranach.org/de/PRIVATE_NONE-P405/ und https://lucascranach.org/de/DE_DHKW-MWMW_Z875/

### Contact Details

dg

### What happened?

KKL-Werke PRIVATE_NONE-P405 und DE_DHKW-MWMW_Z875 ohne Abbildungen

**Comment by WibkeOttweiler** [comment]
Fehler bei DE_DHKW-MWMW_Z875 gefunden; die neue Datei hatte einen Benennungsfehler, ist korrigiert

**Comment by dangoerr** [comment]
Bei P405 ist mit der Benennung im Verzeichnis KKL_Gm alles korrekt. Exifs auch.

**Comment by WibkeOttweiler** [comment]
bei P405 wird das Overall in der Übersicht nicht angezeigt.

**Comment by dangoerr** [comment]
Bei P405 wäre vor allem wichtig, dass der in der Übersicht (Galerieansicht) nicht mehr als Lücke angezeigt wird. EIn Overall ist ja vorhanden. Die Lücke klafft nämlich inzwischen schon sehr lange.
