### ISSUE TITLE
Neue Sammlung für Sammlungsfilter

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#45]
### URL of the buggy page?

https://lucascranach.org/de/search/

### Contact Details

dg

### What happened?

Hey Jorge,
könntest Du die folgende Sammlung noch zum Filter hinzufügen?
Besitzer*in:  Musée international de la Réforme, Genf
Repository:  Musée international de la Réforme, Geneve
Der Eigentümer ist abweichend.

Es wäre also ein neuer Knotenpunkt zu Genf/Geneve nötig.
Anzeige Deutsch und Englisch: "Musée international de la Réforme" 

Bestehenden Genfer Eintrag "Genf, Musée d'Art et d'Histoire" bitte ändern zu "Musée d'Art et d'Histoire. Ebenfalls für beide Sprachen.
Vielen Dank!

**Comment by jhfpereira** [comment]
Hi,

ist eingepflegt und auf die Produktivumgebung ausgespielt.
