### ISSUE TITLE
Bilder werden nicht angezeigt und fehlende Bildinformationen [Functional Bug]: 

### ISSUE THREAD

**Issue by WibkeOttweiler** [lucascranach/cda-orga#47]
### URL of the buggy page?

verschiedene

### Contact Details

Wibke

### What happened?

•	Bei PRIVATE_NONE-P405 werden gar keine Bilder angezeigt 
•	Bei PRIVATE_NONE-P406 werden 2 Bilder nicht angezeigt (12_KOE) und die Bildinformationen fehlen
•	Bei PRIVATE_NONE-P407 werden ebenfalls 2 Bilder nicht angezeigt (12_KOE) und die Bildinformationen fehlen
•	Bei DE_LHW-Lost_NONE-001 wird ebenfalls 1 Bild nicht angezeigt (12_KOE) und die Bildinformationen fehlen

**Comment by dangoerr** [comment]
Zu P405 siehe #44 
Auch P406, P 407 und DE_LHW-Lost_NONE-001 sind im Verzeichnis KKL-Gm korrekt benannt und mit den richtigen Exif-Daten versehen. Müssen die noch einmal neu berechnet werden?

**Comment by cnoss** [comment]
@WibkeOttweiler @dangoerr bei DE_LHW-Lost_NONE-001 sehe ich keine KOE Bilder. Bitte ergänzen und Bescheid sagen (hier) :)

**Comment by WibkeOttweiler** [comment]
habe gerade ergänzt.

**Comment by cnoss** [comment]
Sieht jetzt im internen Bereich gut aus:
https://lucascranach.org/intern/artefacts/de/DE_LHW-Lost_NONE-001/

Suche folgt.
