### ISSUE TITLE
Smartphone Suchfunktion und Scrollleiste

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#51]
### URL of the buggy page?

https://lucascranach.org/de/search/?page=3&kind=UNKNOWN

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

- eine Kleinigkeit: bei der 2. Galerieansicht gibt es jetzt wieder eine angeschnittene Zeile, d.h. die Anpassung der Übersicht auf die jeweilige Bildschirmgröße ist möglicherweise mit der Neuerung nicht übernommen?

- Wir hatten schon darüber gesprochen: Gestern bekam ich nochmal eine Rückmeldung, die beklagt, dass die Suche in der Smartphone-Ansicht nicht funktioniert und dass die Infrarot- und Detailaufnahmen in der Smartphone-Ansicht auch mehr nicht da seien.

Letzteres stimmt nicht, aber tatsächlich habe ich auch festgestellt, dass sie schwer zu finden sind, weil die Thumbs unterhalb der Zoomabbildung angezeigt werden und wenn ich die mit dem Finger einmal berühre, kann ich nicht mehr so leicht weiter nach unten navigieren. Ich muss in dem Fall igendwie wieder weiter nach oben ziehen und dann "mit Schwung" nach unten scrollen, um die unter der zoombaren Abbildung gereihten Infos zu erreichen. Wäre es eine Option hier den rechten Rand neben der zoombaren Abb. (der mir erlaubt nach unten zu scrollen) etwas breiter zu gestalten?

**Comment by cnoss** [comment]
@CranacharchivGunnar bitte pro Bug eine Meldung … ich weiß, es nervt, aber sonst bekommen wir das nicht sauber abgearbeitet.

**Comment by CranacharchivGunnar** [comment]
Sieht gut aus! 

Vielen Dank!
G





>>> Christian Noss ***@***.***> 28.06.22 11.22 Uhr >>>

 @CranacharchivGunnar bitte pro Bug eine Meldung … ich weiß, es nervt,
aber sonst bekommen wir das nicht sauber abgearbeitet.
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID:
***@***.***>
