### ISSUE TITLE
Google Analytics Zahlen seit Freitschaltung des neuen Frontends niedrig 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#52]
### URL of the buggy page?

https://lucascranach.org/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Wir sprachen auch hierüber:
Die von Google Analytics erfassten Besuche des cda sind seit der Freischaltung des neuen Frontends sehr gering.
Wäre sicherlich gut und wichtig, dass wir die Besuche auf den Objektseiten irgendwie wieder mit einbinden, da ich vermute, dass dies auch unser Ranking mit beeinflussen kann...

**Comment by cnoss** [comment]
@CranacharchivGunnar dann müssten wir aber hier auch einen Cookie Consent einbauen. Auf das Ranking hat das keine Auswirkung. Als öffentlicher Träger sollten wir vielleicht insgesamt eher Abstand von Google Analytics nehmen und auf eine Open Source Lösung wechseln, die datenschutz konform ist, z.B. https://matomo.org/

**Comment by CranacharchivGunnar** [comment]
Bin da für jeden Vorschlag zur Verbesserung dankbar, gern matomo, wenn
Du das empfehlen kannst. Unser Cookies Hinweis auf der Startseite
braucht zweifellos eh Aktualisierung. 

Herzlich,
G







>>> Christian Noss ***@***.***> 22.06.22 17.26 Uhr >>>

 @CranacharchivGunnar dann müssten wir aber hier auch einen Cookie
Consent einbauen. Auf das Ranking hat das keine Auswirkung. Als
öffentlicher Träger sollten wir vielleicht insgesamt eher Abstand von
Google Analytics nehmen und auf eine Open Source Lösung wechseln, die
datenschutz konform ist, z.B. https://matomo.org/
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by CranacharchivGunnar** [comment]
Habe da nochmal eine Rückfrage:
Erfasst matomo aktuell auch Besuche, wenn jemand direkt über einen Link auf eine Objektseite (d.h. auf der Objektebene ) des cda gelangt und nicht über die Startseite?
Herzlich,
g

**Comment by markusalterauge** [comment]
Ja, auf den einzelnen Objektseite wurde Matomo ebenfalls integriert.

**Comment by CranacharchivGunnar** [comment]
Super, danke! Dann können wir schließen...
