### ISSUE TITLE
Thumb-Bild auf Übersichtsseite wird nicht angezeigt

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#53]
### URL of the buggy page?

https://lucascranach.org/de/PRIVATE_NONE-P405/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Die Thumb-Abb. https://lucascranach.org/de/PRIVATE_NONE-P405/ wird auf der Übersichtsseite nicht angezeigt.

**Comment by dangoerr** [comment]
Yes, siehe #44
