### ISSUE TITLE
Unterscheidung zwischen Herausgeber und Autor in Literatur 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#54]
### URL of the buggy page?

https://lucascranach.org/de/CH_KMB_177/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

In der Literaturanzeige wird nicht sauber zwischen Herausgeber und Autor getrennt. 
Bei Exhib. Cat. Düsseldorf 2017 ist es richtig, dass zuerst steht: Herausgeber Gunnar Heydenreich, Daniel Görres etc.
Bei Görres 2017B steht auch zuerst "Herausgeber" Daniel Görres, dann Titel etc.
Es muss aber in diesem und allen vergleichbaren Fällen heißen "Autor" Daniel Görres

<html><body>

Exhib. Cat. Düsseldorf 2017 | 201 | No. 108 |  
-- | -- | -- | --
HerausgeberGunnar Heydenreich, Daniel Görres, Beat Wismer                  TitelLucas Cranach der Ältere. Meister - Marke -  Moderne. [anlässlich der Ausstellung "Cranach. Meister - Marke -  Moderne", Stiftung Museum Kunstpalast, Düsseldorf, 08. April 2017 - 30.  Juli 2017]                                                                        Ort der VeröffentlichungMünchen         Jahr der Veröffentlichung2017 | Gunnar Heydenreich, Daniel Görres, Beat Wismer | Lucas Cranach der Ältere. Meister - Marke -  Moderne. [anlässlich der Ausstellung "Cranach. Meister - Marke -  Moderne", Stiftung Museum Kunstpalast, Düsseldorf, 08. April 2017 - 30.  Juli 2017] | München | 2017
Gunnar Heydenreich, Daniel Görres, Beat Wismer
Lucas Cranach der Ältere. Meister - Marke -  Moderne. [anlässlich der Ausstellung "Cranach. Meister - Marke -  Moderne", Stiftung Museum Kunstpalast, Düsseldorf, 08. April 2017 - 30.  Juli 2017]
München
2017
Görres 2017 B | 46 | 108 |  
HerausgeberDaniel Görres                  TitelDer Mönch und der Maler - Luther und Cranach als Vermittler eines neuen Glaubens         Veröffentlichungin Gunnar Heydenreich, Daniel  Görres, Beat Wismer, eds., Lucas Cranach der Ältere. Meister - Marke -  Moderne. [Exhib. Cat. Düsseldorf 2017]                                                               Ort der VeröffentlichungMunich         Jahr der Veröffentlichung2017                                                      Seiten44-51 | Daniel Görres | Der Mönch und der Maler - Luther und Cranach als Vermittler eines neuen Glaubens | in Gunnar Heydenreich, Daniel  Görres, Beat Wismer, eds., Lucas Cranach der Ältere. Meister - Marke -  Moderne. [Exhib. Cat. Düsseldorf 2017] | Munich | 2017 | 44-51
Daniel Görres
Der Mönch und der Maler - Luther und Cranach als Vermittler eines neuen Glaubens
in Gunnar Heydenreich, Daniel  Görres, Beat Wismer, eds., Lucas Cranach der Ältere. Meister - Marke -  Moderne. [Exhib. Cat. Düsseldorf 2017]
Munich
2017
44-51

</body>
</html>[Exhib. Cat. Düsseldorf 2017](https://lucascranach.org/de/CH_KMB_177/#) 	201 	No. 108 	
Herausgeber	Gunnar Heydenreich, Daniel Görres, Beat Wismer
Titel	Lucas Cranach der Ältere. Meister - Marke - Moderne. [anlässlich der Ausstellung "Cranach. Meister - Marke - Moderne", Stiftung Museum Kunstpalast, Düsseldorf, 08. April 2017 - 30. Juli 2017]
Ort der Veröffentlichung	München
Jahr der Veröffentlichung	2017
[Görres 2017 B](https://lucascranach.org/de/CH_KMB_177/#) 	46 	108 	
**Herausgeber**	Daniel Görres
Titel	Der Mönch und der Maler - Luther und Cranach als Vermittler eines neuen Glaubens
Veröffentlichung	in Gunnar Heydenreich, Daniel Görres, Beat Wismer, eds., Lucas Cranach der Ältere. Meister - Marke - Moderne. [Exhib. Cat. Düsseldorf 2017]
Ort der Veröffentlichung	Munich
Jahr der Veröffentlichung	2017
Seiten	44-51

**Comment by cnoss** [comment]
@CranacharchivGunnar nix verstehen an dieser Stelle … das müssen wir uns mal zusammen anschauen bitte

**Comment by cnoss** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/2807738/175088753-6dfab694-52e6-40ce-b6d5-7297e2263d34.png">

Ist in den Daten mit `Role=unknown` zugeordnet und ROLE unknown wird im Frontend der Role Publisher zugeordnet … müsste entweder in den Daten als "Autor" zugeordnet werden, oder wir sagen dem Frontend, dass UNKNOWN immer bei Autor angezeigt werden soll. Oder es gibt noch ne andere Lösung :)

**Comment by CranacharchivGunnar** [comment]
Hi,
Helen schickte diesesen Screenshot der Erfassungsmaske in TMS, d.h.
der/die Autor*in wird immer konkret und in Abgrenzung von Herausgeber*in
erfasst. Wenn diese Role/Funktion  "Autor*in" von Euch im Export
nirgends zu finden ist, müssten wir d:kult konktatieren? 

Herzlich,
G










>>> Christian Noss ***@***.***> 22.06.22 18.38 Uhr >>>

 
 Ist in den Daten mit Role=unknown zugeordnet und ROLE unknown wird im
Frontend der Role Publisher zugeordnet … müsste entweder in den Daten
als "Autor" zugeordnet werden, oder wir sagen dem Frontend, dass UNKNOWN
immer bei Autor angezeigt werden soll. Oder es gibt noch ne andere
Lösung :)
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID:
***@***.***>

**Comment by CranacharchivGunnar** [comment]
Hi Christian,
wenn sich die Angaben "Autor*in" im Export nicht finden lassen, dann
wäre ich dankbar, wenn Ihr bitte temporär im Online Bereich folgende
Umbenennung vornehmen könntet:

Deutsch: "Herausgeber:" umbenennen in "Autor / Herausgeber:" 

Englisch: "Publisher:" umbenennen in "Author / Editor:" 


Dann ist es zumindest nicht mehr falsch, so wie aktuell.... und wir
können ggf. mit dem nächsten Export darauf achten, dass die Daten mit
ausgelesen werden....
Danke!

Herzlich,
Gunnar



        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        PublisherGunnar HeydenreichTitleHerstellung, Grundierung und
Rahmung der Holzbildträger in den Werkstätten Lucas Cranachs
d.Ä.Publicationin Ingo Sandner, Wartburg-Stiftung 
Eisenach and Fachhochschule Köln, eds., Unsichtbare Meisterzeichnungen 
auf dem Malgrund. Cranach und seine Zeitgenossen, Exhib. Cat.
EisenachPlace of PublicationRegensburgYear of
Publication1998Pages181-200



>>> Gunnar Heydenreich 23.06.22 15.05 Uhr >>>
Hi,
Helen schickte diesesen Screenshot der Erfassungsmaske in TMS, d.h.
der/die Autor*in wird immer konkret und in Abgrenzung von Herausgeber*in
erfasst. Wenn diese Role/Funktion  "Autor*in" von Euch im Export
nirgends zu finden ist, müssten wir d:kult konktatieren? 

Herzlich,
G










>>> Christian Noss ***@***.***> 22.06.22 18.38 Uhr >>>

 
 Ist in den Daten mit Role=unknown zugeordnet und ROLE unknown wird im
Frontend der Role Publisher zugeordnet … müsste entweder in den Daten
als "Autor" zugeordnet werden, oder wir sagen dem Frontend, dass UNKNOWN
immer bei Autor angezeigt werden soll. Oder es gibt noch ne andere
Lösung :)
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID:
***@***.***>

**Comment by cnoss** [comment]
ist jetzt so implementiert:
Deutsch: "Herausgeber:" umbenennen in "Autor / Herausgeber:"
Englisch: "Publisher:" umbenennen in "Author / Editor:"

**Comment by CranacharchivGunnar** [comment]
Auch korrekt so. Wunderbar!
Danke!
G





>>> Christian Noss ***@***.***> 04.08.22 12.05 Uhr >>>

 Closed #54 as completed.
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID:
***@***.***>
