### ISSUE TITLE
DE_BRD-KSVC_M337 wird nicht angezeigt

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#55]
### URL of the buggy page?

https://lucascranach.org

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Das Objekt 
https://lucascranach.org/admin/DE_BRD-KSVC_M337
wird derzeitig im Online-Bereich nicht angezeigt.

**Comment by CranacharchivGunnar** [comment]
https://lucascranach.org/de/DE_BRD-KSVC_M337/

**Comment by cnoss** [comment]
@CranacharchivGunnar dazu gibt es in den Rohdaten zwei Verzeichnisse:
- DE_BRD-KSVC_M337_FR50A
- DE_BRD-KSVC_M337_FR050A

Vermutlich liegt es daran. Welchen soll ich nehmen? Im Zweifel mal kurz fonen. Ich kann allerdings nur am Montag diese Woche :)

<img width="1534" alt="Bildschirmfoto 2022-06-25 um 09 25 02" src="https://user-images.githubusercontent.com/2807738/175763322-032b9cde-89b3-42f3-aa00-da1f0932350d.png">
<img width="1315" alt="Bildschirmfoto 2022-06-25 um 09 23 31" src="https://user-images.githubusercontent.com/2807738/175763327-b211e0be-9763-43b5-a083-1a036a956be1.png">

**Comment by CranacharchivGunnar** [comment]
Mein Kommentar war nicht angekommen:

Danke fürs schnelle prüfen.

Die korrekte Bezeichnung lautet:
DE_BRD-KSVC_M337_FR050A

Früher hatten wir
DE_BRD-KSVC_M337_FR-none, weil wir irrtümlich davon ausgingen, dass dieses Bild bei FR nicht verzeichnet ist.
Dann wurden die TMS Nummer und die Abbildungen offenbar umbenannt, aber dabei die "0" vergessen.

Wenn Du die Abbildungen in dem Ordner DE_BRD-KSVC_M337_FR50A bitte alle umbenennst in
DE_BRD-KSVC_M337_FR050A...., dann sollte es funktionieren.

Danach kann der Ordner DE_BRD-KSVC_M337_FR-none auch gelöscht werden.

Vielen Dank! Hoffe, wir haben die Daten damit bald sauber....

Herzlich,
Gunnar

**Comment by cnoss** [comment]
Hi, ist jetzt hier verfügbar:
https://lucascranach.org/intern/artefacts/de/DE_BRD-KSVC_M337/

Suche folgt. @CranacharchivGunnar passt das so?

**Comment by CranacharchivGunnar** [comment]
Perfect!
Danke!
G

**Comment by CranacharchivGunnar** [comment]
Danke fürs schnelle prüfen.

Die korrekte Bezeichnung lautet:
DE_BRD-KSVC_M337_FR050A

Früher hatten wir 

DE_BRD-KSVC_M337_FR-none, weil wir irrtümlich davon ausgingen, dass
dieses Bild bei FR nicht verzeichnet ist.

Dann wurden die TMS Nummer und die Abbildungen offenbar umbenannt, aber
dabei die "0" vergessen.

Wenn Du die Abbildungen in dem Ordner DE_BRD-KSVC_M337_FR50A bitte alle
umbenennst in 

DE_BRD-KSVC_M337_FR050A...., dann sollte es funktionieren.

Danach kann der Ordner DE_BRD-KSVC_M337_FR-none auch gelöscht werden.

Vielen Dank! Hoffe, wir haben die Daten damit bald sauber....


Herzlich,
Gunnar




>>> Christian Noss ***@***.***> 25.06.22 9.27 Uhr >>>

 @CranacharchivGunnar dazu gibt es in den Rohdaten zwei Verzeichnisse:
  
* DE_BRD-KSVC_M337_FR50A 
* DE_BRD-KSVC_M337_FR050A 
 Vermutlich liegt es daran. Welchen soll ich nehmen? Im Zweifel mal kurz
fonen. Ich kann allerdings nur am Montag diese Woche :)
 
 
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID:
***@***.***>

**Comment by CranacharchivGunnar** [comment]
Hi, 

ja, das sieht gut aus und kann so online gehen...
Danke!

G

 





>>> Christian Noss ***@***.***> 04.08.22 11.37 Uhr >>>

 Hi, ist jetzt hier verfügbar:
 https://lucascranach.org/intern/artefacts/de/DE_BRD-KSVC_M337/
 Suche folgt. @CranacharchivGunnar passt das so?
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID:
***@***.***>
