### ISSUE TITLE
ES_FLG_2911 wird nicht angezeigt 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#56]
### URL of the buggy page?

https://lucascranach.org

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

ES_FLG_2911 wird nicht angezeigt.

... ist ein weiteres, der insgesamt 3 vorhandenen Gemälde, die aktuell im cda online noch nicht angezeigt werden.

**Comment by cnoss** [comment]
Hi, 

das Objekt hat hat in den Daten die OID *FR-none* imd Datei- und Ordnernamen aber *FR222C*. Was ist zu tun?

lg- c

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/2807738/175975298-4f57d571-e4fd-440e-a3ec-2d5079279c00.png">

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/2807738/175975341-6b80b7ce-a676-4660-910d-24e267462388.png">

**Comment by cnoss** [comment]
Hi, jetzt hier verfügbar:
https://lucascranach.org/intern/artefacts/de/ES_FLG_2911/

@CranacharchivGunnar passt das so?

**Comment by CranacharchivGunnar** [comment]
Ebeonso gut, kann online gehen...
Danke!

g





>>> Christian Noss ***@***.***> 04.08.22 11.36 Uhr >>>

 Hi, jetzt hier verfügbar:
 https://lucascranach.org/intern/artefacts/de/ES_FLG_2911/
 @CranacharchivGunnar passt das so?
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID:
***@***.***>
