### ISSUE TITLE
Anzeige "Overall Overview" images wünschenswert 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#59]
### URL of the buggy page?

https://lucascranach.org

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Anordnung auf der Objektebene entweder links unter der feststehenden Abbildung (in gleicher Breite wie die max. Breite der feststehenden Abbildung) oder vielleicht auf der rechten Seite zwischen "Beschreibung / Interpretation / Kommentare" und "Zugehörige Werke". Dann sollen diese "overall overview" und auch "zugehörige Werke" standardmäßig immer ausgeklappt sein.
Können wir gern nochmal besprechen...

**Comment by yannic-bruegger** [comment]
Hi zusammen, ist das das Feature für die Anzeige der zusammenhängenden Werke wie Diptychons, Triptychons,und Polyptychons? Falls ja kann ich geren dafür mal einen UI-Entwurf machen und schauen, wie es am besten aussehen könnte.

**Comment by yannic-bruegger** [comment]
Beispielbild für Triptychon. Ich finde den Ansatz hier fein aber wenn es um komplexere Polyptychons geht, wird es schwierig die in einem Overview-Bild darzustellen.

![Image](https://github.com/lucascranach/cda-orga/assets/36576062/fd14b32e-92b1-4213-aff0-41a3926b56d5)

**Comment by markusalterauge** [comment]
Den Ansatz finde ich ganz cool. Würde beim Diptychon wahrscheinlich auch noch funktionieren. Wenn aber beim Triptychon noch ein Retabelaufsatz und eine Predella dazu kommen, könnte es vielleicht unübersichtlich werden. Dann gibt es auch von Triptychons Flügel Innen- und Flügel Außenseiten. Und bei Polyptychons müsste man auch erstmal ganz verstehen, wie die zusammengesetzt werden.

**Comment by markusalterauge** [comment]
Für einen Prototypen ohne etwas im Importer zu ändern kann man in den Keywords erkennen, um welche Art von "ptychon" es sich handelt:

`keywords[x].term`
`010201 = Diptychon`
`010202 = Triptychon`
`010203 = Polyptychon`

Zudem steht dann im Titel des Bildes, in eckigen Klammern, an welcher Stelle das Bild sitzt. (Z.B. [Mitteltafel] oder [Rechter Flügel, Innenseite])
Bilder die zusammen gehören haben die gleiche ID. Der einzige unterschied ist die letzte Ziffer. Hier findet eine alphabetische Nummerierung statt. Beispiel am Triptychon: (a-e) (A-E)
Dabei scheint die Mitteltafel immer "A", "a" zu sein.
Dann kommt der linke Flügel "B", "b" (Wenn es eine Außenseite gibt hat diese "C", "c")
Dann kommt der rechte Flügel "C", "c" ( Wenn es eine Außenseite gibt hat die Innenseite "D", "d", die Außenseite "E", "e")
Dann kommt die Predella "D", "d"
Dann kommt der Retabelaufsatz "E", "e"

**Comment by CranacharchivGunnar** [comment]
Sorry, hatte schon am 5.1. geantwortet (ist aber nicht im System gelandet):

Ja, für Diptychen und Triptychen sieht das mit den verblassten Teilen gut aus (macht aber vermutlich einige Arbeit, die Abb. aufzubereiten), bei komplexeren Werken, wird dann die Übersichtsabbildung von z.B. einem Flügelgemälde zu klein, um es noch erkennen zu können. Deshalb die Idee an oberer Stelle die bisherige Abb. zu belassen und darunter die zugehörige Overall_overview Abb. anzuordnen. 

Dazu sollten wir noch überlegen, ob / wie die Abb. einbeziehen, die unter "Zugehörige Werke" verlinkt angezeigt werden.

Alternative bessere Idee:
Links die Overall-Thumb-Abb. so unverändert belassen, den Textblock in der Mitte so belassen (bezieht sich ja hinsichtlich der Maße auch nur auf die Mitteltafel oder den Flügel), aber dann rechts neu oberhalb von "Provenienz" die Overall-Overview Abb. einfügen und direkt darunter den Button "Zugehörige Werke" ausgeklappt einfügen. Erst darunter dann "Ausstellungen", "Quellen", "Forschungsgeschichte..." 

Herzlich,
Gunnar

**Comment by yannic-bruegger** [comment]
Ich baue hierzu mal ein Design, damit wir drüber abstimmen können. Das plane ich für nächste Woche ein, wenn sich an der Prio nichts mehr ändert. Danke, für euer Feedback!

**Comment by yannic-bruegger** [comment]
Habe ich dich grob so richtig vertanden?

![Image](https://github.com/lucascranach/cda-orga/assets/36576062/02d6e03e-34db-4c7c-8afe-240187686e9c)

**Comment by yannic-bruegger** [comment]
Hi Yannic,
hier nachfolgend das gesammelte Feedback zu dem Entwurf:

Ja, grundsätzlich so richtig...
Danke Euch für das schnelle und hilfreiche Feedback und dass wir die Position dort schon mal alle gut finden. Mal sehen, was Christian meint. Er hat ja diesbezüglich immer neue Ideen...(cc)
G


>>> "Herrschaft, Jana" <[jana.herrschaft@kunstpalast.de](javascript:void(0);)> 28.02.2024 12:49 >>>
Die Gesamtansicht an dieser Stelle erachte ich auch als gut und sinnvoll.
Mit den ausgeklappten Abbildungen der Flügel hab ich so mein Problem, da sie das Gesamtlayout zerschießen (um so mehr, wenn es noch mehr Teile sind). Die Informationen zu Provenienz, Ausstellungen etc. verschieben sich einfach zu weit nach unten.
Ich kann Daniels Argument zu der Anzahl der Teile bei Polyptychen gut nachvollziehen, dann müssten die Infos zu Provenienz etc aber in die Mitte/ unter den Permalink rutschen, damit das Layout wieder funktioniert.

Beste Grüße
Jana

**Comment by yannic-bruegger** [comment]
Ich habe mit Christian heute mal drüber gesprochen. 

- Christian würde gerne mal versuchen, ob wir technisch eine "on the fly" generierte Gesamtansicht erstellen können. So können wir das aktuelle Teil hervorheben und auch in Zukunft Interaktivität ermöglichen. Wir müssten an den Abbildungen erst einmal nichts ändern.

- Ob die zugehörigen Werke ein- oder ausgeklappt sind, können wirgerne auch recht kurzfristig entscheiden.

![Image](https://github.com/lucascranach/cda-orga/assets/36576062/710da2ff-ca3d-4fb6-b069-2adfcb62aea8)

**Comment by CranacharchivGunnar** [comment]
Soeben nochmal mit Christian besprochen... On the fly wird nicht überzeugend möglich
![grafik](https://github.com/lucascranach/cda-orga/assets/106104186/a65fc8ad-6a5e-4ca8-be57-ca783a504012)

**Comment by yannic-bruegger** [comment]
Top, dann wieder der Stand: :)

![Image](https://github.com/lucascranach/cda-orga/assets/36576062/e513472b-7466-41c5-9b8a-350075193882)

**Comment by yannic-bruegger** [comment]
@cnoss ich gebe dir das Issue mal, damit du die Bilddaten reinwerfen kannst. Wünsche viel Erfolg :) Danach kannst du es gerne wieder an mich schubsen.

**Comment by cnoss** [comment]
@yannic-bruegger @CranacharchivGunnar 

Das ist jetzt mal für zwei Datensätze implementiert. Hier ein kurzer Videokommentar:

<iframe width="560" height="315" src="https://www.youtube.com/embed/CELRDsK3_Q8?si=2YLM6UXGKhBKbbNz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

Hier der Link: [Kleines Flügelretabel mit der Auferstehung Christi](https://lucascranach.org/intern/artefacts/de/DE_MHK_GK11a/)

**Comment by CranacharchivGunnar** [comment]
Finalmente! Sciebo sagt mir, dass ich die Testabb. vor zwei Jahren hochgeladen habe...
Danke Dir!
Spontane Kommentare:
- finde Position und Größe der Abb. Overall-overview gut so - gern erstmal so belassen
- Ja, wenn kein Diptychon und damit kein Overall-overview etc. dann bitte die Zeilen wieder nach unten schieben, so wie aktuell im cda (sieht nicht gut aus, wenn der Textblock oben am Rand klebt)
- Beschriftung m.E. nicht zwingend nötig, da die Textzeile "Zugehörige Werke" direkt darunter steht
- Bitte keine zusätzliche Einsortierung der Abbildung unten bei den Thumnails vornehmen, da diese Abbildungen dort schon vorhanden sind (= Dopplung) [umgekehrt können sie aber dort nicht einfach entnommen werden, da keine eindeutige Kennzeichnung]
- Könntest Du bitte für die anderen 15 Werke die Overall-Overview auch entsprechend einspielen, so dass wir das mal in einem breiteren Spektrum sehen und beurteilen können? Hier die anderen: https://th-koeln.sciebo.de/s/d4A3PTXNvKtBkJJ
Alles weitere gern am Dienstag...
Herzlich,
Gunnar

**Comment by cnoss** [comment]
- [CZ_RKFK_NONE-001](https://lucascranach.org/intern/artefacts/de/CZ_RKFK_NONE-001)
- [DE_AGGD_7c](https://lucascranach.org/intern/artefacts/de/DE_AGGD_7c)
- [DE_KAZW_NONE-KAZW001C](https://lucascranach.org/intern/artefacts/de/DE_KAZW_NONE-KAZW001C)
- [DE_KAZW_NONE-KAZW001F](https://lucascranach.org/intern/artefacts/de/DE_KAZW_NONE-KAZW001F)
- [DE_MHK_GK11b](https://lucascranach.org/intern/artefacts/de/DE_MHK_GK11b)
- [DE_SKD_GG1906B](https://lucascranach.org/intern/artefacts/de/DE_SKD_GG1906B)
- [DE_AGGD_7a](https://lucascranach.org/intern/artefacts/de/DE_AGGD_7a)
- [DE_KAZW_NONE-KAZW001A](https://lucascranach.org/intern/artefacts/de/DE_KAZW_NONE-KAZW001A)
- [DE_KAZW_NONE-KAZW001D](https://lucascranach.org/intern/artefacts/de/DE_KAZW_NONE-KAZW001D)
- [DE_KAZW_NONE-KAZW001G](https://lucascranach.org/intern/artefacts/de/DE_KAZW_NONE-KAZW001G)
- [DE_MHK_GK11c](https://lucascranach.org/intern/artefacts/de/DE_MHK_GK11c)
- [DE_AGGD_7b](https://lucascranach.org/intern/artefacts/de/DE_AGGD_7b)
- [DE_KAZW_NONE-KAZW001B](https://lucascranach.org/intern/artefacts/de/DE_KAZW_NONE-KAZW001B)
- [DE_KAZW_NONE-KAZW001E](https://lucascranach.org/intern/artefacts/de/DE_KAZW_NONE-KAZW001E)
- [DE_MHK_GK11a](https://lucascranach.org/intern/artefacts/de/DE_MHK_GK11a)
- [DE_SKD_GG1906BB](https://lucascranach.org/intern/artefacts/de/DE_SKD_GG1906BB)

**Comment by CranacharchivGunnar** [comment]
Sehr schön, danke Dir!
- Also die Größe finde ich OK, auch wenn z.B. ein Predellenbild auf der hochformatigen Übersichtsabbildung nur zu erahnen ist.
- Auch finde ich es gut, das overall overview Bild durch zwei Linien oben und unten einzufassen.
-  Allerdings sollte bitte die Textzeile "Zugehörige Werke" und der Pfeil zum Ausklappen unter der overall overview Abb. angeordnet sein.
Warum: Das Altarretabel selbst ist in der Überschrift benannt und das links sichtbare Teilelement [z.B. Mitteltafel] ist nicht ein zugehöriges Werk, sondern Teil dieses Werkes "Altarretabel". Wenn jetzt die Überschrift "Zugehörige Werke" über der Overall-Overview Abb. des Altars steht, dann ist das inhaltlich missverständlich, denn eigentlich handelt es sich um "Ein Teil des Werkes" - aber diese zusätzliche Überschrift würde auch nicht ganz korrekt sein, denn links in der Überschrift steht ja bereits "Altarretabel... [Mitteltafel]". Wenn die Zeile "Zugehörige Werke" unter der Overall-overview Abb. steht, ist es wieder korrekt, weil der Nutzer dann mit dem Pfeil tatsächlich die anderen zu dem Altar zughörigen Werke eingeblenden kann...
- DE_SKD_GG1906... Schlage vor, dass Du das Overall-overview in dem Datensatz nochmal löschst und ich nochmal neu mit dem Gesamtpaket erstelle. Tatsächlich haben da die Flügel und Mitteltafel unterschiedliche FR-Nummern und vermutlich bin ich beim Kopieren der overall-overview durcheinander geraten, da ja die jeweils die gleiche sein sollte... 
- Happy Easter und Dank!!
- G

**Comment by CranacharchivGunnar** [comment]
Hi Christian,
habe jetzt ein größeres Paket mit den Overall_overview Abb. fertig und schicke Dir am Montag den Datenstick mit der Hauspost.
Falls die Abb. händisch in bestehende Ordner einzusortieren sind, könnte vielleicht Yannic das übernehmen? (Daniel muss auf Grafik fokussieren).
Wäre schön, wenn wir das auch in der kommenden Woche mit dem finalen Export und den kleinen Baustellen in diesem Zusammenhang abhaken können.
Bei den Overall_overview hatte ich in Github noch hinterlassen, dass die Abb. bitte OBERHALB von dem Text "Zugehörige Werke" und dem Pfeil zum Ausklappen angeordnet sein sollte.
Herzlich,
Gunnar

**Comment by cnoss** [comment]
Ich muss die noch rechnen das dauert. Schaffe ich wenn es gut läuft nächste Woche … die muss ich nachschieben. Die bestehenden können wir jetzt schon mit hoch schieben.

**Comment by CranacharchivGunnar** [comment]
Mission completed! Dank in die Runde!
Und demnächst kommen noch weitere overall-overview Bilder hinzu...
