### ISSUE TITLE
BU ergänzen

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#6]
In Textblock unter den Abb. einfügen: Künstler (an erster Stelle)

**Comment by jhfpereira** [comment]
Aktueller Stand
![Bildschirmfoto 2020-03-15 um 18 32 22](https://user-images.githubusercontent.com/1864692/76706910-56554d00-66eb-11ea-8a50-ecd9e2a912db.png)

Die unschönen Abstände sind wahrscheinlich auf den Wegfall von Bulma zurückzuführen.
Da müsste man nochmal nachziehen.
