### ISSUE TITLE
Im Literaturarchiv ist die Verlinkung zu den Objektdatensätzen nicht mehr aktiv.

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#62]
### URL of the buggy page?

https://lucascranach.org/publications

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Die Verlinkung von den Publikationen zu den Objektdatensätzen funktioniert derzeitig nicht mehr, vermutlich seit dem Launch des neuen Frontends. Bisher wurden unter den Publikationsdatensätzen jeweils die Thumbs der Gemälde angezeigt, die in der Literatur besprochen sind...

**Comment by cnoss** [comment]
@cnoss das hat vor ein paar Tagen noch funktioniert … da muss ein anderes Problem greifen … ich mach mich mal auf die Suche :/

**Comment by cnoss** [comment]
Letzte Zeile aaskommentiert (Trail & Error )

```
        $sql = "SELECT l.*, l.ObjNr as objNr, o.ObjIdentifier as frNr,\n"
        . "t.Title as title, m.Value as repo,\n"
        . "i.Overall_Image as image\n"
        . "FROM Lit_LinkedObject l\n"
        . "JOIN Object o\n"
        . "ON l.ObjNr = o.ObjNr\n"
        . "JOIN ObjectTitle t\n"
        . "ON o.UId = t.Object_UId\n"
        . "JOIN MultipleTable m\n"
        . "ON o.UId = m.Object_UId\n"
        . "JOIN Images i\n"
        . "ON o.UId = i.Object_UId\n"
        . "WHERE l.Object_UId LIKE '$id'\n"
        . "AND t.DisplayOrder <= 2\n"
        . "AND t.Language LIKE '$selectedLanguage'\n"
        . "AND (m.Type LIKE 'Besitzer' OR m.Type LIKE 'Repository')\n";
//        . "AND m.Language LIKE '$selectedLanguage'";
```
