### ISSUE TITLE
Zahlreiche pdf Dateien werden aktuell nicht angezeigt

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#63]
### URL of the buggy page?

https://lucascranach.org/de/PRIVATE_NONE-P322/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Derzeitig werden im Online-Bereich zahlreiche pdf Dateien nicht angezeigt, offenbar diejenigen, die in TMS nicht nochmal zusätzlich über einen Dateinamen verknüpft sind, sich aber auf dem Server befinden.
Zahlreiche pdf Dateien haben wir einfach mit der ID in den Unterordnern auf den Server geladen, aber in TMS nicht zusätzlich bei den Technolog. Untersuchungen mit dem Dateinamen eingegeben. Diese pdfs sollten aber unbedingt auch wieder angezeigt werden! Bisher erschienen die einfach mit einem PDF Icon zusammen mit den Thumbabbildungen auf der Objektebene. ..
z.B.
PRIVATE_NONE-P322_FR_none_2019_Report.pdf
UK_NGL_6511-1_FR015_2015_Catalogue-entry
US_IMA_2000-344_FR218_1999-2016_analysis-report-002
PRIVATE_NONE-P054_FR-none_2008_Overall-002
u.v.m.
insgesamt sollten im cda aktuell etwa 1.190 pdfs angezeigt werden.
Könnten direkt unter den Thumbs auch mit dem Dateinamen erscheinen.

[Möglicherweise hängt das auch damit zusammen, dass zuletzt noch im Onlinebereich Links aus TMS zu pdf Dateien angezeigt wurden, zu denen es keine verknüpften pdfs gab und diese Links hattest Du (Christian) ja zurück gesetzt.

Indem auf diese aktuell nicht angezeigten pdfs in den Texten mehfach referenziert wird, sollten wir die bitte  möglichst bald wieder hineinholen...
Danke!

**Comment by cnoss** [comment]
Hi,

ich hab eine eigene Schublade "Dokumente" eingeführt (unter Abbildungen):
https://lucascranach.org/intern/artefacts/de/AT_KHM_GG6739/

@CranacharchivGunnar passt das so? Da sind alle PDFs des Objekts drin

**Comment by CranacharchivGunnar** [comment]
Das sieht auf den ersten Blick ebenfalls sehr gut aus.
In der Schublade werden die pdf-Dateinamen angezeigt [öffnen lassen sie
sich noch nicht, aber das liegt sicherlich daran, dass Du die Funktion
zunächst im Adminbereich gebaut hast].
Sobald das Online geht, werde ich nochmal umfangreicher prüfen...

Herzlich,
G



>>> Christian Noss ***@***.***> 04.08.22 13.21 Uhr >>>

 Hi,
 ich hab eine eigene Schublade "Dokumente" eingeführt (unter
Abbildungen):
 https://lucascranach.org/intern/artefacts/de/AT_KHM_GG6739/
 @CranacharchivGunnar passt das so? Da sind alle PDFs des Objekts drin
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID:
***@***.***>
