### ISSUE TITLE
MX_MNSC_6525_FR-none wird online nicht angezeigt (im internen Bereich ist es sichtbar) 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#64]
### URL of the buggy page?

https://lucascranach.org/intern/artefacts/de/MX_MNSC_6525/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Objekt wird online nicht angezeigt

**Comment by jhfpereira** [comment]
Hier liegt das Problem wahrscheinlich darin, dass für das Objekt kein Anfangs- bzw. End-Datum hinterlegt ist.
Habe dazu auch in die Roh-Daten geschaut. Schon dort fehlt das Datum, weshalb es sehr wahrscheinlich im TMS korrigiert werden muss.

**Comment by cnoss** [comment]
@CranacharchivGunnar @dangoerr habt ihr hier mal geguckt?

**Comment by CranacharchivGunnar** [comment]
Ja, das sollte sich mit dem Einlesen des nächsten Exportes aus TMS klären. 
Helen und Jana erfassen gerade 80 neue Gemälde und sobald der ansteht, dürfte dieser Punkt entfallen...
