### ISSUE TITLE
Eckige Klammern bei Online-Quellenangaben werden nicht angezeigt 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#65]
### URL of the buggy page?

https://lucascranach.org/intern/artefacts/de/PRIVATE_NONE-P528/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Bei Online-Link-Quellenangaben werden die Einträge nicht in eckigen Klammern angezeigt.
Auch werden diese Angaben in Schwarz und nicht in Grau angezeigt, dadurch erhöht sich ihre Wertigkeit, was zu einer Fehlinterpretation führen kann. z.B.

https://lucascranach.org/intern/artefacts/de/PRIVATE_NONE-P528/

Bei Datierung:
Sotheby's online database, accessed 16.03.2022
[Friedländer, Rosenberg 1979, no. 388L]

Bitte online Quellenangaben in grau und mit eckigen Klammern anzeigen. Danke!

**Comment by cnoss** [comment]
Auf dem internen Server gefixt … bitte mal checken.

**Comment by CranacharchivGunnar** [comment]
Hi,
danke, das sieht so schon sehr gut aus.
Der Link-Eintrag [Sotheby's online database, accessed 16.03.2022] sollte jedoch bei Zuschreibung und Datierung einschließlich der eckigen Klammern bitte auch in grauer  Schrift (nicht in Schwarz) angezeigt werden. Siehe Screenshot. 

![Unbenannt-1](https://user-images.githubusercontent.com/106104186/194384035-be52d228-4672-400e-bc18-9c252e75ef22.jpg)

**Comment by cnoss** [comment]
Done … @CranacharchivGunnar  bitte noch mal checken und kurz feedbacken, dann stelle ich das scharf :)

**Comment by CranacharchivGunnar** [comment]
Sorry, aber jetzt fehlen die eckigen Klammern bei der Online Quelle wieder, die oben schon da waren und die Onlinequellen sind weiterhin schwarze und die anderen Quellen graue Schrift (beide sollen aber graue Schrift sein).
![Unbenannt-1](https://user-images.githubusercontent.com/106104186/198040337-c8489557-1da1-4fd5-8b1d-fd0e321c9312.jpg)

**Comment by CranacharchivGunnar** [comment]
Completed!
