### ISSUE TITLE
[Functional Bug]: Personenfilter liefert aktuell teilweise falsche Ergebnisse

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#66]
### URL of the buggy page?

https://lucascranach.org/de/search/?page=1&kind=UNKNOWN&from_year=1470&to_year=max&filters=subject%3A010402010139

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Hi,
aktuell scheint der Personenfilter um etwa eine Person verrutscht zu sein. 
Michael Meyenburg liefert 182 Treffer - zeigt dabei dann die Lutherbildnisse
Philipp von Wittelsbach, Bischof - liefert 74 Treffer - zeigt dabei Melanchthon

Martin Luther6
Michael Meyenburg182
Moritz Buchner1
Nicholas de Backer1
Nikolaus Seidel1
Otto Brunfels2
Paulus von Berge1
Philipp Melanchthon1
Philipp von Wittelsbach, Bischof74

**Comment by CranacharchivGunnar** [comment]
Der Fehler beginnt bei 
Georg Spalatin (0) Treffer
danach folgt Georg von Weidebach mit 4 Treffern, die aber Georg Spalatin zeigen, 
danach alle um jeweils eine Zeile verschoben....
(Ich glaube, diesen Fehler hatten wir vor längerer Zeit schon einmal, erinnere aber nicht mehr, woran es lag...)

**Comment by CranacharchivGunnar** [comment]
Sorry, wollte das nicht als Closed markieren

**Comment by cnoss** [comment]
@jhfpereira hast Du ne Idee, woran das liegen könnte? Kommen da die Daten schon falsch aus der API?

**Comment by jhfpereira** [comment]
@cnoss Das beschrieben Problem liegt an nicht aktuelle Filter-JSON-Dateien in der API-Komponente. Diese JSON-Dateien entstehen mit jedem Import von Export-Daten und müssen dann per Hand in das API-Repository kopiert, commited und dann deployed werden.

Habe die aktuellsten Filter-JSON-Dateien in der API hinterlegt und die API für die interne und die öffentliche Suche mit diesen aktuellen Daten neu deployed. Sollte jetzt wieder sauber sein.

Ich gehe davon aus, dass sich bei einem der letzteren Exporte etwas am Thesaurus getan hat und das an mir vorbei gegangen ist oder ich es einfach nur vergessen habe. Da muss eine bessere Lösung für ausgearbeitet werden. Ist sonst zu fehleranfällig, wie in diesem Falle.
Es gab schon mal die Idee diese JSON-Files als Volume in den API-Container zu mounten. Kommt in auf die TODO-Liste.

@CranacharchivGunnar: Könntest du es bei Gelegenheit nochmal testen und das Issue hier dann schließen, wenn es auch aus deiner Seite wieder sauber ist?

**Comment by CranacharchivGunnar** [comment]
Hi Jorge,
online sieht das jetzt wieder gut aus. Danke!!

(Hinweis: Ja, es werden auch beim nächsten Export wieder neue Namen
hinzukommen und insofern wäre da in Zukunft, eine Lösung, die diese
Erweiterungen berücksichtigt, sicherlich gut...)
Herzlich,
Gunnar





>>> "Jorge H. F. Pereira" ***@***.***> 21.08.22 18.10 Uhr
>>>

 @cnoss Das beschrieben Problem liegt an nicht aktuelle
Filter-JSON-Dateien in der API-Komponente. Diese JSON-Dateien entstehen
mit jedem Import von Export-Daten und müssen dann per Hand in das
API-Repository kopiert, commited und dann deployed werden.
 Habe die aktuellsten Filter-JSON-Dateien in der API hinterlegt und die
API für die interne und die öffentliche Suche mit diesen aktuellen Daten
neu deployed. Sollte jetzt wieder sauber sein.
 Ich gehe davon aus, dass sich bei einem der letzteren Exporte etwas am
Thesaurus getan hat und das an mir vorbei gegangen ist oder ich es
einfach nur vergessen habe. Da muss eine bessere Lösung für
ausgearbeitet werden. Ist sonst zu fehleranfällig, wie in diesem Falle.
 Es gab schon mal die Idee diese JSON-Files als Volume in den
API-Container zu mounten. Kommt in auf die TODO-Liste.
 @CranacharchivGunnar: Könntest du es bei Gelegenheit nochmal testen und
das Issue hier dann schließen, wenn es auch aus deiner Seite wieder
sauber ist?
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID:
***@***.***>
