### ISSUE TITLE
Ein Gemälde wird Online noch nicht angezeigt.

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#68]
### URL of the buggy page?

https://lucascranach.org

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Hi,

also, im Moment werden online 2361 Gemälde angezeigt.
Im alten Admin-Bereich werden noch immer 2363 Gemälde angezeigt.
Eines der fehlenden Werke ist MX_MNSC_6525_FR-none, damit wären es 2362.

Fehlt also Online noch ein Gemälde, welches seit der Umstellung auf das neue Frontend verschüttet ist.
Ich weiß nicht, wie ich es finden kann, ohne alle 2361 Gemälde einzeln vergeleichend durchzusehen.
Habt Ihr eine Idee?

**Comment by cnoss** [comment]
@CranacharchivGunnar ich kann noch mal Listen ziehen aus der Datenbank und von uns … schaff ich aber erst demnächst

**Comment by CranacharchivGunnar** [comment]
Kein Problem, das eilt nicht...




>>> Christian Noss ***@***.***> 05.11.22 21.12 Uhr >>>

 @CranacharchivGunnar ich kann noch mal Listen ziehen aus der Datenbank
und von uns … schaff ich aber erst demnächst
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID:
***@***.***>
