### ISSUE TITLE
Daten zu GWN_LC_HVI-7_6 am Frontend nicht auf aktuellem Stand

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#70]
Bei GWN_LC_HVI-7_6 hat sich am Stand des Frontends bei den letzten Gemäldeexporten scheinbar nichts geändert (nur Gemälde geupdated?). Sollte dies so sein, bitte mit dem heutigen Export (28.02.23) auch die Graphiken berücksichtigen.

**Comment by jhfpereira** [comment]
@cnoss Sieht danach aus, als müssten die Objektseiten für die Grafiken neu generiert werden.
Auf jeden Fall schon mal für den internen, wahrscheinlich aber auch für den öffentlichen Bereich.
Für den öffentlichen Bereich dann vermutlich ebenfalls auf Basis des 20230315-Exports. Sofern da nichts drin ist, was bei den Grafiken nicht in den öffentlichen Bereich darf.
