### ISSUE TITLE
Bitte bei Gelegenheit Ordner für Dateiumbenennung bereitstellen

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#78]
### URL of the buggy page?

x

### Contact Details

DG

### What happened?

Bitte bei Gelegenheit die Ordner G_DE_UBH_* für Bildaustausch/Umbenennung zur Verfügung stellen. Danke!

**Comment by dangoerr** [comment]
Hey, hast Du mir einen Ordner zu Heidelberg schon irgendwo hingelegt?
VG

**Comment by dangoerr** [comment]
Sorry, war mal so frei den issue wieder neu zu öffnen oder fehlt mir eine Info?

**Comment by cnoss** [comment]
Liegt nun hier: /home/dgoerres/umbenennung

**Comment by dangoerr** [comment]
Habe die Dateien umbenannt, liegen in /home/dgoerres/Umbenannt. Die kannst Du gerne wieder in die Live-Version schieben.

**Comment by cnoss** [comment]
@dangoerr kannst Du hier mal schauen, ob der gewünschte Effekt eingetreten ist? Ich weiß leider nicht, wie ich das überprüfen kann: https://lucascranach.org/de/intern/search/

**Comment by dangoerr** [comment]
An vielen Stellen hat es sich verbessert, es ist aber noch nicht alles behoben. Sorry, ich fürchte daher müssen wir noch eine zweite Runde drehen. Der Server ließ es nicht zu, dass ich das nochmal komplett hochlade, daher habe ich es Dir auf Sciebo gepackt:
https://uni-bonn.sciebo.de/s/lm0wsgb1VMpMAbM

Im Moment sind zwei Datensätze online nicht aufrufbar (404-Fehler). Ich vermute, das liegt wiederum nicht an Dateibenennungen. Wir können aber natürlich erst einmal schauen, wenn die neuen Dateien online sind.
G_DE_UBH_Salem26-5RES_fol4v
G_DE_UBH_Salem33-14RES

**Comment by cnoss** [comment]
@dangoerr hab Dir einen einen neuen Ordner angelegt. Der sollte genug Platz haben … der Umweg über Sciebo ist seeeeeeehr umständlich:



![Image](https://github.com/lucascranach/cda-orga/assets/2807738/744f761c-9f93-4cd7-8c8b-fc8a047e5209)

**Comment by dangoerr** [comment]
Yep, ist mir auch viel lieber so. Die Daten sind jetzt oben.

**Comment by dangoerr** [comment]
Hier ist ja inzwischen alles Bestens. Nur eine Kleinigkeit ist noch übriggeblieben:  Bei DE_UBH_Salem95-5RES ist noch ein Platzhalter für eine Reverse-Abbildung zu sehen, die es nicht mehr gibt.

**Comment by dangoerr** [comment]
Hi Yannic, das hier wäre eines der Issues, von denen ich vermute, dass sie mit wenig vorausgehenden Aufwand geschlossen werden könnten. Es geht nur noch um den einen Platzhalter...

**Comment by yannic-bruegger** [comment]
Schaue ich mir an, danke!

**Comment by dangoerr** [comment]
Top, danke
