### ISSUE TITLE
Google Analytics ausbauen (Redaktioneller Bereich)

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#81]
… und durch etwas datenschutzfreundliches ersetzen. In dem Zuge bitte auch Cookie Consent ausbauen oder anpassen. 

Bitte max 1 PT investieren.

**Comment by markusalterauge** [comment]
Habe Matomo auf dem Server installiert und Google Analytics entfernt.
Habe Opt-Out in das Impressum gehackt
`<script>
        const url ="https://lucascranach.org/impressum"
        const actualUrl = new URL(window.location.toLocaleString());
        if(url === actualUrl.href){
            setTimeout(function(){
                var matomoScript = document.createElement('script');
                matomoScript.type = 'text/javascript';
                matomoScript.src = "https://lucascranach.org/matomo/index.php?module=CoreAdminHome&action=optOutJS&divId=matomo-opt-out&language=auto&showIntro=1"
                document.getElementsByTagName('head')[0].appendChild(matomoScript)
            },100)
        }
    </script>` 
Wenn du einen eleganteren Weg kennst, bitte mitteilen.

Falls die Lösung ausreicht, würde ich die Cookie Consent raus nehmen.
