### ISSUE TITLE
Übersichtsseite Gemälde: Anzeige vollständige Zeilen 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#88]
### URL of the buggy page?

https://lucascranach.org/de/search/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Bei der Übersichtsdarstellung der Gemälde und der Auswahl der "zweiten" Ansicht (mit Thumbs ohne jegliche Textdaten) sollte sich die Anzahl der angezeigten Thumbs bitte auf sichtbare vollständige Reihen reduzieren (haben wir schon häufiger besprochen, ist möglicherweise mit der Überführung auf den neuen Server erneut herausgeflogen)

**Comment by CranacharchivGunnar** [comment]
sehe gerade, dass es bei der Reiterfunktion "Gemälde" doch funktioniert und nur bei der Reiterfunktion "Alle Werke" hakelt...

**Comment by cnoss** [comment]
Hi, da hatte Jorge noch mal ne überarbeitete Lösung gebaut. Wir haben das gerade noch mal im Team diskutiert… durch die Flexibilität, die wir jetzt für verschiedene Viewports (Tablet, Desktop, ...) und die verschiedenen Darstellungsformen (Kachel mit Text, Tabelle, etc.) ist das "auffüllen" der Zeilen fast unmöglich, bzw. lässt sich nur unzuverlässig und EXTREM umständlich un kompliziert abbilden, dass ich das erst mal zurück gestellt habe. Wir gucken nun mal, wie andere mit dem Problem umgehen, in der Hoffnung da eine leichtgewichtigere Lösung zu finden.

**Comment by CranacharchivGunnar** [comment]
Hi, danke für die Info.
Beim Reiter "Gemälde" funktioniert es weiterhin, beim Reiter "Alle Werke" nicht. Bei den Reitern Archivalien und Literatur ist es nicht nötig.
Wenn es also bei "Alle Werke" perspektivisch noch funktionieren könnte, wäre das sehr gut, da ich diese Funktion regelmäßig nutze...

**Comment by yannic-bruegger** [comment]
Hier müsstet ihr mich noch einmal abholen, was genau gewünscht ist. Könnt ihr mir Bilder dazu einstellen oder wir machen mal einen Call aus. Danke :)

**Comment by CranacharchivGunnar** [comment]
Ich glaube, das ist einfacher mit einem Call... Hättest Du morgen (Mi) am späteren Vormittag Zeit?

**Comment by CranacharchivGunnar** [comment]
Manchmal muss man nur Geduld haben... Habe soeben nochmal getestet und jetzt funktioniert es auch beim Reiter "Alle Werke" sowie beim Wechsel zwischen den Reitern und Ansichten problemlos...
Schließe mal den Fall und melde mich, falls das Problem nochmal erscheint...
