### ISSUE TITLE
Archivalien: drei Vorschaubilder fehlen noch...

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#89]
### URL of the buggy page?

https://lucascranach.org/artefacts/de/DE_StSWR_KR-1513/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Super, dass jetzt nahezu alle Abb. aufleuchten!!
Bei drei Archivalien fehlen auf der Archivalien-Übersichtsseite noch die Vorschaubilder (bei Öffnung des Datensatzes sind die Abb. vorhanden)

https://lucascranach.org/artefacts/de/DE_StSWR_KR-1513/
https://lucascranach.org/artefacts/de/DE_StSWR_KR-1523/
https://lucascranach.org/artefacts/de/DE_StSWR_KR-1536/

**Comment by cnoss** [comment]
sind non vollständig
