### ISSUE TITLE
Archivalien werden noch nicht in richtiger Reihenfolge angezeigt 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cda-orga#92]
### URL of the buggy page?

https://lucascranach.org/artefacts/de/DE_ThHStAW_EGA_Reg-Bb_1772_13r_16v/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Eine Nutzerin machte uns darauf aufmerksam, dass die Archivalien in der Übersichtsdarstellung nicht entsprechend der Datierung angezeigt werden. Hierfür sollte der Eintrag im Feld "Sortierreihenfolge" (wie bei den Gemälden auch) genutzt werden.

**Comment by markusalterauge** [comment]
An welcher Stelle soll die Sortierung vorgenommen werden: Schon im Importer (in der json) oder erst beim Erzeugen von cranach-artefacts? @cnoss

**Comment by markusalterauge** [comment]
Habe die SortingNumber im Importer hinzugefügt.
https://github.com/lucascranach/importer/commit/cadcfd0bf6a4edfee115600affeba93f92f65258

**Comment by cnoss** [comment]
@CranacharchivGunnar könntet ihr mal gucken, ob die Reihenfolge nun passt, oder mir sagen, wie ich es prüfen kann?

**Comment by cnoss** [comment]
@markusalterauge hm … aus der API kommt noch nix. Kannst Du das mal mit Volker zeitnah klären, dass wir den Bug hier weg bekommen:


![Image](https://github.com/lucascranach/cda-orga/assets/2807738/162818f1-9dfc-4e23-985e-ca6e50dee32f)

**Comment by markusalterauge** [comment]
Habe die searchSortingNumber hinzugefügt und die Bulk Dateien auf dem Server aktualisiert.
Bitte drüber schauen, ob die Reihenfolge nun passt:
https://lucascranach.org/de/intern/search/?page=1&kind=archivals

**Comment by cnoss** [comment]
@markusalterauge wie ist hier der Stand? Ist das online auf Prod? Wenn ja: bug bitte weg sortieren … wenn nein, bitte dafür sorgen, dass es auf prod sichtbar ist. Dankeee

**Comment by CranacharchivGunnar** [comment]
Auf der öffentlichen Seite ist die Sortierreihenfolge noch immer nicht korrigiert. 
In der internen Vorschau sieht es gut aus!

**Comment by markusalterauge** [comment]
Wir warten noch den aktuellen Gemäldeexport ab und würden dann den Export in den öffentlichen Bereich veröffentlichen. Danach sollte die Reihenfolge ebenfalls korrigiert sein.
Ich kann, falls das mit dem Gemäldeexport zu lange dauern sollte, aber auch vorher schon den öffentlichen Bereich updaten.

**Comment by CranacharchivGunnar** [comment]
Finalmente perfetto!
