### ISSUE TITLE
URL nach Serverumzug mit zusätzlichem Verzeichnis 

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#95]
### URL of the buggy page?

z. B. https://lucascranach.org/artefacts/de/UK_NGL_6538/

### Contact Details

DG

### What happened?

Ein ausgewähltes Werk trägt in der URL das zusätzliche Verzeichnis .../artefacts/..., was nicht identisch mit dem unten angegeben Permalink https://lucascranach.org/de/UK_NGL_6538/ ist.

**Comment by markusalterauge** [comment]
Hi,
das "artefacts" sollte nun nicht mehr in der url auftauchen.

**Comment by dangoerr** [comment]
Hallo Markus,

yep, ist es, vielen Dank! Und natürlich auch Dir herzlich willkommen an Bord.

Beste Grüße
Daniel


Von: Markus Alterauge ***@***.***>
Gesendet: Montag, 21. August 2023 10:53
An: lucascranach/cda-orga ***@***.***>
Cc: Görres, Daniel ***@***.***>; Author ***@***.***>
Betreff: Re: [lucascranach/cda-orga] URL nach Serverumzug mit zusätzlichem Verzeichnis (Issue #95)


Hi,
das "artefacts" sollte nun nicht mehr in der url auftauchen.
