### ISSUE TITLE
Fehlende Werke in Galerieansicht

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#96]
### URL of the buggy page?

DE_KSVC_M418; DE_BStGS_6246; PRIVATE_NONE-P527a

### Contact Details

DG

### What happened?

Die drei oben genannten Werke werden in der Galerie nicht angezeigt, obwohl das der Fall sein sollte. Die ersten beiden sind schon lange im cda, das letzte m. W. nach beim letzten Gemälde-Export hinzugekommen.

**Comment by yannic-bruegger** [comment]
Zwischenstand:
Im Import scheinen alle Werke da zu sein.
Die API liefert wie Werke nicht aus.

**Comment by yannic-bruegger** [comment]
Update:
Ich vermute, dass das Attribut _imgSrc_ in den Metadaten wichtig sind, damit Werke von der API angeboten werden. Bei den drei Werken ist dort nichts angegeben.

**Comment by dangoerr** [comment]
OK, danke. Ist vielleicht hier das selbe Problem?
https://github.com/lucascranach/cda-orga/issues/89#issue-1811900555
