### ISSUE TITLE
Bei Anzeige von Literatur-Primärquellen fehlt die Kategorie "Offizin"

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#97]
### URL of the buggy page?

z. B. https://lucascranach.org/de/HBG_HII-154_270

### Contact Details

DG, 01577-3480310

### What happened?

Bei der Literaturangabe auf Objektebene fehlt die Kategorie "Offizin". Diese ist nur bei den Literatureinträgen relevant, die als Quellen/Primärquellen ("primary source") gekennzeichnet sind, in Abgrenzung zur Literatur aus dem Bereich Forschungsliteratur. Bisher erscheint nur der Autor, an gleicher Stelle müsste auch die Information zur Offizin (Druckwerkstatt) im XML auffindbar sein und sollte mit ausgegeben werden. Bitte Kategorie nach "Titel" und vor "Ort der Veröffentlichung" einfügen. Bei Rückfragen Telefonnummer oben.
Beispiel für Literatureintrag "cda.VD 16 L 6689": Hier fehlt die Information "Offizin: Johann Schott"

Im Literaturbereich des cda selbst wird die Information grundsätzlich mit ausgegeben, aber vermischt mit der Info zum Autor: 
https://lucascranach.org/de/literature-30317
Hier erscheint also als "Herausgeber/in, Autor/in": Johann Schott, Martin Luther. Korrekt müsste Luther als Autor genannt werden und Johann Schott in eigener Zeile als "Offizin". Achtung, dies gilt wie gesagt nur für die primary sources, bei der Forschungsliteratur ist die gemeinsame Kategorie Herausgeber/in, Autor/in korrekt.

### Additional context & Screenshots

![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/b4c5e0cc-1279-42a3-9fa5-9984982cc2e1)
![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/9925ab51-e5b3-4573-860b-707628ed7307)

**Comment by dangoerr** [comment]
Nachtrag: Das gleiche müsste auch auf der Ebene der Druckexemplare eingesetzt werden, wie ja ebenfalls eine "Quelle" angegeben ist.

![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/99049da8-636e-4c2c-9d38-27bca8e01b44)

**Comment by cnoss** [comment]
@dangoerr hab ich mal umgebaut … kannst Du mal bei relevanten Objekten schauen, ob das passt … ich hab das direkt in der PROD Version gemacht: https://lucascranach.org/de/literature-30317

**Comment by dangoerr** [comment]
Vielen Dank, das passt. Daher gerne auch in der Quellenangabe auf der Objektebene übernehmen.
Und noch etwas Kosmetisches und daher nicht dringend: Ideal wäre natürlich, wenn das Feld "Offizin" ausgeblendet wäre, falls es keinen Eintrag hat.


> Nachtrag: Das gleiche müsste auch auf der Ebene der Druckexemplare eingesetzt werden, wie ja ebenfalls eine "Quelle" angegeben ist.
> 
> ![grafik](https://private-user-images.githubusercontent.com/91158095/263197373-99049da8-636e-4c2c-9d38-27bca8e01b44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTI4NDcsIm5iZiI6MTcwNzgxMjU0NywicGF0aCI6Ii85MTE1ODA5NS8yNjMxOTczNzMtOTkwNDlkYTgtNjM2ZS00YzJjLTlkMzgtMjdiY2E4ZTAxYjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA4MjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYzNmY2E5N2IzZDg4MTNkYzcyMzY4MzhkZmFlZTMzNzczMDljNmUyYmQ2MmNlMjFmMjc5N2EyOTYwNDhiNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jB8270Z-7mHlEBdZxEOoMJSg8k2PNXfSxekzlBiXkIQ)
