### ISSUE TITLE
Rückkehr von Suchergebnis nicht über Button "zur Werksuche"/"go to works search" möglich 

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#98]
### URL of the buggy page?

z. B. https://lucascranach.org/de/search/?page=1&kind=works&filters=catalog%3Acatalog.KKL.I

### Contact Details

DG

### What happened?

Ich habe eine Suche/Filterung durchgeführt und ein Werk aus dem Ergebnis angeklickt. Wenn ich von dort zurück zum Suchergebnis möchte, kann ich das nur über den "Back"-Button des Browsers tun. Benutze ich den Button "zur Werksuche"/"go to works search" geht mein Suchergebnis verloren. 

### Additional context & Screenshots

![grafik](https://github.com/lucascranach/cda-orga/assets/91158095/0b263acf-26ab-41c5-94b8-24cdc03942e5)

**Comment by yannic-bruegger** [comment]
To do: Mit Parameter aus der Objektebene übergeben und dann Filter/Suche aus local storage laden.
