### ISSUE TITLE
Abb. in der Übersicht der Druckgraphiken fehlt

### ISSUE THREAD

**Issue by dangoerr** [lucascranach/cda-orga#99]
### URL of the buggy page?

https://lucascranach.org/de/ANO_HVI-8_7-1

### Contact Details

DG

### What happened?

Un der Übersicht auf https://lucascranach.org/de/ANO_HVI-8_7-1 wird die Abbildung zu DE_SBB_Libri-impr-rari-qu190 nicht an gezeigt. Beim Dantensatz selbst sind alle Abbildungen da.

**Comment by cnoss** [comment]
@dangoerr Ist der Dateiname so korrekt? mit diesem Schnipsel? `2019_fol1r_2019`

![Image](https://github.com/lucascranach/cda-orga/assets/2807738/f2295d68-457d-4c2b-a117-fa65324f4f53)

**Comment by cnoss** [comment]
ist nun vorhanden … hab die Bilder noch mal neu generiert
